### ISSUE TITLE
Dataprovider cannot be loaded dynamically

### ISSUE THREAD

**Issue by Gyllion** [kartik-v/yii2-export#106]
Hello there, Kartik. Thanks for making this great extension.

What I miss in the export menu extension is a way to dynamically update the dataprovider (with javascript) and to reload the export menu.

At the moment I am using a datepicker with range and the kartik gridview. As soon as the user changes a date, the gridview is deleted and added with a new dataprovider. This is the same for the export menu. The problem is, that the JS I wrote is colliding with the kartik JS and no files can be exported anymore.

**Comment by kartik-v** [comment]
Not sure what you exactly are trying... but you can render ExportMenu dynamically via renderAjax and update to the latest release v1.3.4.
