### ISSUE TITLE
Bootstrap related issue.

### ISSUE THREAD

**Issue by yasir47** [kartik-v/yii2-export#107]
I just install yii2-export the problem i facing is export dropdown not working when i troubleshoot the issue there i find out my bootstrap version is 3.3.4 when i forcefully add bootstrap version 3.1 it works fine but create problem with version 3.3.4 .

**Comment by kartik-v** [comment]
You need to check your application CSS and JS dependencies and see if there are other plugins or JS causing errors.

The yii2-export works fine with Bootstrap v3.3.6 as seen on the demos page.
