### ISSUE TITLE
Installation error: kartik-v/yii2-export v1.2.2 requires phpoffice/phpexcel 1.8.0 -> no matching package found

### ISSUE THREAD

**Issue by anuri73** [kartik-v/yii2-export#108]
When installing the kartik-v/yii2-export I receive the following error. Your requirements could not be resolved to an installable set of packages

```
Problem 1
    - kartik-v/yii2-export v1.2.2 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
    - kartik-v/yii2-export v1.2.1 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
    - kartik-v/yii2-export v1.2.0 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
    - kartik-v/yii2-export v1.1.0 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
    - kartik-v/yii2-export v1.0.0 requires phpoffice/phpexcel 1.8.0 -> no matching package found.
    - kartik-v/yii2-export dev-master requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
    - kartik-v/yii2-export dev-master requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
    - kartik-v/yii2-export v1.2.3 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.x-dev].
    - Can only install one of: phpoffice/phpexcel[dev-develop, 1.8.x-dev].
    - Can only install one of: phpoffice/phpexcel[dev-develop, 1.8.x-dev].
    - Installation request for phpoffice/phpexcel dev-develop -> satisfiable by phpoffice/phpexcel[dev-develop].
    - Installation request for kartik-v/yii2-export @dev -> satisfiable by kartik-v/yii2-export[dev-master, v1.0.0, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.2.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by nadeemse** [comment]
Hi How can I fix this issue, 

Problem 1
    - kartik-v/yii2-export v1.0.0 requires phpoffice/phpexcel 1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0].
    - kartik-v/yii2-export v1.1.0 requires phpoffice/phpexcel 1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0].
    - kartik-v/yii2-export v1.2.0 requires phpoffice/phpexcel 1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0].
    - kartik-v/yii2-export v1.2.1 requires phpoffice/phpexcel 1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0].
    - kartik-v/yii2-export v1.2.2 requires phpoffice/phpexcel 1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0].
    - kartik-v/yii2-export v1.2.3 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0, 1.8.1].
    - kartik-v/yii2-export v1.2.4 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0, 1.8.1].
    - kartik-v/yii2-export v1.2.5 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0, 1.8.1].
    - kartik-v/yii2-export v1.2.6 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0, 1.8.1].
    - kartik-v/yii2-export v1.2.7 requires phpoffice/phpexcel ~1.8.0 -> satisfiable by phpoffice/phpexcel[1.8.0, 1.8.1].
    - kartik-v/yii2-export v1.2.8 requires phpoffice/phpexcel ~1.8 -> satisfiable by phpoffice/phpexcel[1.8.0, 1.8.1].
    - kartik-v/yii2-export dev-master requires phpoffice/phpspreadsheet ~1.0 -> satisfiable by phpoffice/phpspreadsheet[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - kartik-v/yii2-export 1.3.x-dev requires phpoffice/phpspreadsheet ~1.0 -> satisfiable by phpoffice/phpspreadsheet[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - kartik-v/yii2-export v1.2.9 requires phpoffice/phpspreadsheet ~1.0 -> satisfiable by phpoffice/phpspreadsheet[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - kartik-v/yii2-export v1.3.0 requires phpoffice/phpspreadsheet ~1.0 -> satisfiable by phpoffice/phpspreadsheet[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - kartik-v/yii2-export v1.3.1 requires phpoffice/phpspreadsheet ~1.0 -> satisfiable by phpoffice/phpspreadsheet[1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0].
    - phpoffice/phpexcel 1.8.1 requires ext-xml * -> the requested PHP extension xml is missing from your system.
    - phpoffice/phpexcel 1.8.0 requires ext-xml * -> the requested PHP extension xml is missing from your system.
    - phpoffice/phpspreadsheet 1.4.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpoffice/phpspreadsheet 1.3.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpoffice/phpspreadsheet 1.3.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpoffice/phpspreadsheet 1.2.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpoffice/phpspreadsheet 1.2.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpoffice/phpspreadsheet 1.1.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - phpoffice/phpspreadsheet 1.0.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for kartik-v/yii2-export @dev -> satisfiable by kartik-v/yii2-export[dev-master, 1.3.x-dev, v1.0.0, v1.1.0, v1.2.0, v1.2.1, v1.2.2, v1.2.3, v1.2.4, v1.2.5, v1.2.6, v1.2.7, v1.2.8, v1.2.9, v1.3.0, v1.3.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mbstring.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by kartik-v** [comment]
Update via composer to latest release and let know.
