### ISSUE TITLE
implement easy way to change exported file description

### ISSUE THREAD

**Issue by mikk150** [kartik-v/yii2-export#113]
Right now the string "Grid export generated by Krajee ExportMenu widget (yii2-export)" is hard-coded in code(and is not changable by public property)

**Comment by kartik-v** [comment]
You need to use PHP Excel properties to control what you need to be displayed. Check the events allowed by the extension to  manipulate PHP Excel library. You can set the `onInitExcel` property to a Closure function for example to manipulate PHP Excel settings.
