### ISSUE TITLE
Not exporting after change to filter - Dynagrid

### ISSUE THREAD

**Issue by AntoninSlejska** [kartik-v/yii2-export#125]
The description of this issue is fast the same as by: https://github.com/kartik-v/yii2-export/issues/46

The difference is, that I use Dynagrid. The solution from the previous issue does not work in Dynagrid.

See:
- the test website: http://example.yii-test.slejska.de/index.php?r=client%2Findex
- and the code: 

```
$fullExportMenu = ExportMenu::widget([
    ...
    'pjaxContainerId' => 'kv-pjax-container',
]);
```

(https://github.com/AntoninSlejska/yii-test/blob/master/example/views/client/index.php#L31)

```
<?= DynaGrid::widget([
    ...
    'gridOptions' => [
        ...
        'pjax' => true,
        'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
        ...
]); ?>
```

(https://github.com/AntoninSlejska/yii-test/blob/master/example/views/client/index.php#L60)

**Comment by metola** [comment]
Hi AntoninSlejska , did you find the solution?

**Comment by AntoninSlejska** [comment]
@metola The simplest solution is to disable pjax.
