### ISSUE TITLE
Bootstrap Dropdown not working with ExportMenu

### ISSUE THREAD

**Issue by aesnyahsan** [kartik-v/yii2-export#129]
All dropdowns stop working when I add this code
`echo ExportMenu::widget([ 'dataProvider' => $dataProvider, 'columns' => $gridColumns ]);`

After some testing, I realize the addition of `'js/bootstrap.min.js',` in my Asset file is conflicting with Kartik Export Menu...

so when I remove `'js/bootstrap.min.js',` ExportMenu widget including all other dropdown on that specific page start working.. but dropdown on other pages stop working..

In my project I need to use both of them... 
Can you please suggest any solution?

**Comment by mitramir** [comment]
This is the solution that fixed the problem, add the following to .js file:

$(document).ready(function() {
    $(".dropdown-toggle").dropdown();
});

I add it to view/index.php 
`$this->registerJs( $(document).ready(function() {
    $('.dropdown-toggle').dropdown();
});",
	View::POS_END, 'ecommerceProductJs'
	);`

**Comment by castilloidalberto93** [comment]
Please help me with the same error, a conflict between ExportMenu and bootstrap.min.js, I do not understand the previous explanation. Thanks

**Comment by Xavatar5** [comment]
Either add `$this->registerJs("$(document).ready(function() { $('.dropdown-toggle').dropdown(); });", View::POS_END);` to your view file like mitramir said.

Or if you want more permanent solution, you can edit **bootstrap-selectpicker.js**:
just change this block of code
`        this.$newElement.on('show.bs.dropdown', function() {
          if (version.major > 3 && !that.dropdown) {
            that.dropdown = that.$button.data('bs.dropdown');
            that.dropdown._menu = that.$menu[0];
          }
        });`
to this:
`        this.$newElement.on('show.bs.dropdown', function() {
          if (version.major > 3 && !that.dropdown) {
            if (!that.$button.data('bs.dropdown')) {
              that.$button.dropdown();
            }
            that.dropdown = that.$button.data('bs.dropdown');
            that.dropdown._menu = that.$menu[0];
          }
        });`
