### ISSUE TITLE
Export does not adapt new dataProvider 

### ISSUE THREAD

**Issue by nagaokashi** [kartik-v/yii2-export#132]
Thank you very much for great extension.
I'm using this extension and this works fine. But I got below problem.
When I load default dataProvider (ex: id = 1), export works fine. 
But, when I add some filter like ID then use Pjax to load dataProvider again, this still exports the old data of dataProvider.
The Gridview works fine for both.

My code:
` public function search($params)
    {
        $query = Datsan::find()->where([
            'id' => empty($params['ids']) ? 1 : explode(",", $params['ids']),
        ]);

```
    // add conditions that should always apply here
    $dataProvider = new ActiveDataProvider([
        'query' => $query,
    ]);
    return $dataProvider;
}`
```

View file
`                echo ExportMenu::widget([
                    'dataProvider' => $dataProviderQuanLySan,
                    'columns' => $gridColumns,
                    'clearBuffers' => true,
                    'exportConfig' => [
                        ExportMenu::FORMAT_CSV => false,
                        ExportMenu::FORMAT_HTML=> false,
                        ExportMenu::FORMAT_TEXT => false,
                        ExportMenu::FORMAT_PDF => false,
                        ExportMenu::FORMAT_EXCEL => [],
                        ExportMenu::FORMAT_EXCEL_X => [],
                    ],
                    'dropdownOptions' => [
                        'label' => Yii::t('app','Download'),
                        'class' => 'btn btn-primary'
                    ],
                    'target' => '_self',
                    'showConfirmAlert' => false,
                    'fontAwesome' => true,
                ]);
                echo '</div>';
                echo '</div>';

```
            echo '<div class="qlysan-gridview">';
            $dataProviderQuanLySan->pagination->pageSize=100;
            echo GridView::widget([
                'dataProvider' => $dataProviderQuanLySan,
                'columns' => $gridColumns,
                'pjax'=>true,
                'pjaxSettings'=>[
                    'neverTimeout'=>true,
                    'options'=>['id' => 'datsan-grid-pjax'],
                ],
                'responsive'=>true,
                'hover'=>true,
                'resizableColumns'=>true,
            ]);
            echo '</div>';
        }
        ?>
```

`

**Comment by swati-clarion** [comment]
Hi Kartik,

I have same issue , I am using "kartik-v/yii2-export": "@dev". I have a  search filter at top and when I apply search filter, the view page displays only filtered results but when I export data to csv, excel etc. , all records are exported. 

Here is my code:
<?php echo $this->render('_searchInHand', ['model' => $searchModel]); ?>
	<?php echo ExportMenu::widget([
		'dataProvider' => $dataProvider,
		'columns' => $gridColumns,
		'filename' => 'On Hand Inventory for '.date("Y-m-d H:i:s"),
		'fontAwesome' => true,
		'pjaxContainerId' => 'kv-pjax-container',
		'clearBuffers' => true,
		'initProvider' => true,
		'target' => ExportMenu::TARGET_BLANK,
		'exportConfig' => [
		 ExportMenu::FORMAT_TEXT => false,
		 //ExportMenu::FORMAT_PDF => false,
		 ExportMenu::FORMAT_HTML => false,
		 //ExportMenu::FORMAT_EXCEL_X => false,		 
		],		
		'dropdownOptions' => [
			'label' => 'Export All',
			'class' => 'btn btn-primary'
		]
		]);
		echo \kartik\grid\GridView::widget([
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'columns' => $gridColumns,
		'pjax' => true,
		'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
	]);
	?>

Thanks in Advance!

**Comment by kartik-v** [comment]
`ExportMenu` does not recognize what you are filtering through the `GridView` which is entirely a separate component on the page. You need to pass the updated filtered `dataProvider` to ExportMenu again if you need to achieve that.

**Comment by wbawor** [comment]
Very nice extension although I cannot get it working with filtering like it does in your grid-advanced-1 demo. I display `$dataProvider->totalCount` just before `ExportMenu::widget` and it reports 1. GridView also shows 1 filtered record but Export exports all 13 records. What I am missing? Could you give a hint or maybe provide model/view/controller for grid-advanced-1? Thank you!
