### ISSUE TITLE
Not able to export Data.

### ISSUE THREAD

**Issue by neerajs046** [kartik-v/yii2-export#134]
I have successfully integrated your module in my yii2 project and it is showing the export button but I am not able to export data. When I click on the export type nothing happens.

**Comment by jsivakumaran** [comment]
I am also having the same problem.  There is a pop up but nothing gets downloaded.

**Comment by rizrob66** [comment]
I am also having the same problem. Like jsivakumaran. Please help us.

**Comment by rizrob66** [comment]
I updated to last version, and It works again. I hope it helps.

**Comment by pramodtheapplab** [comment]
I have successfully integrated your module in my yii2 project and it is showing the export button but I am not able to export data. When I click on the export type nothing happens. and i check the console that shows "Uncaught TypeError: jQuery(...).exportdata is not a function" . please help me what should i do?

**Comment by kartik-v** [comment]
You seem to have either invalid configuration / code on your page - OR you do not have a proper install. Just update via composer to the latest release and check.
