### ISSUE TITLE
Not able to donwload pdf file

### ISSUE THREAD

**Issue by gaganmcp** [kartik-v/yii2-export#139]
initially it was giving error like:
The pdf rendering library 'mPDF' was not found or installed at path '/home/USERNAME/_protected/vendor/mpdf/mpdf'
once I add  'pdfLibraryPath' => '@vendor/kartik-v/mpdf', then it is not giving any error but pdf is not being download.....excel and csv working fine.

**Comment by kartik-v** [comment]
The default pdfLibrary uses mpdf and the `kartik-v/mpdf` project has been abandoned and redirected to use `mpdf/mpdf` library.

Ensure you have updated release of this yii2-export extension - the default pdfLibraryPath setting is now  `@vendor/mpdf/mpdf`

**Comment by pptyasar** [comment]
How to update @kartik-v

**Comment by SnitramDev** [comment]
Same error here. Followed instructions from here:
https://github.com/kartik-v/yii2-export

**Comment by kartik-v** [comment]
You need to run composer update and ensure you have latest release of mpdf library 7.x release.
