### ISSUE TITLE
Does not work on Yii2 basic without additional libs and settings

### ISSUE THREAD

**Issue by tgamanov** [kartik-v/yii2-export#140]
For correct using of this lib you need 
1. Add next libs
  "kartik-v/yii2-grid": "@dev",
  "kartik-v/yii2-mpdf": "@dev"
to composer.json and update it
2.  Add to config/web.php in 'components':
'modules' => [
        'gridview' =>  [
            'class' => '\kartik\grid\Module'
            // enter optional module parameters below - only if you need to  
            // use your own export download action or custom translation 
            // message source
            // 'downloadAction' => 'gridview/export/download',
            // 'i18n' => []
        ]
    ]

Thank you.

**Comment by kartik-v** [comment]
This extension should install dependencies if you are installing via composer (it has dependency to `yii2-dynagrid` and `phpexcel` and these should get installed automatically).
