### ISSUE TITLE
expose the ability  to set cell DataType manually to avoid formula syntax check

### ISSUE THREAD

**Issue by ihipop** [kartik-v/yii2-export#143]
the default behavior  of PHPEXCEL is to set cell datatype via `DefaultValueBinder`
the whole work follow is
[yii2-export render the Cell with  setCellValue()](https://github.com/kartik-v/yii2-export/blob/8b60570fb3f541c2fac8ea4ea8e221d6a28e8750/ExportMenu.php#L1372),then
setCellValue Call  [bindValue()](https://github.com/PHPOffice/PHPExcel/blob/7d1c140974a4988f8a9739d167335d24fb59955e/Classes/PHPExcel/Cell.php#L206)  and then [dataTypeForValue](https://github.com/PHPOffice/PHPExcel/blob/7d1c140974a4988f8a9739d167335d24fb59955e/Classes/PHPExcel/Cell/DefaultValueBinder.php#L73)   to detect the `dataType` then pass the `datatype` to [setValueExplicit](https://github.com/PHPOffice/PHPExcel/blob/7d1c140974a4988f8a9739d167335d24fb59955e/Classes/PHPExcel/Cell/DefaultValueBinder.php#L61)

The problem is that if some string is start with ‘=’, it will treated as `formula` by  [dataTypeForValue](https://github.com/PHPOffice/PHPExcel/blob/7d1c140974a4988f8a9739d167335d24fb59955e/Classes/PHPExcel/Cell/DefaultValueBinder.php#L73) 

if a string is `==hell world==`,[this  will cause error  and throw out an Exception  to stop](https://github.com/PHPOffice/PHPExcel/blob/7d1c140974a4988f8a9739d167335d24fb59955e/Classes/PHPExcel/Cell.php#L291) when rendering  cell  because it was treated as a `formula` and can't pass the formula syntax check and this behavior  won’t be overwride by `onRenderDataCell`

![20160601184229](https://cloud.githubusercontent.com/assets/423077/15707097/6c72e386-2829-11e6-9e79-dad2c1116e4e.jpg)

Thus to add an space to the string can bypass this issue,I think that the best way to solve this is to expose the `cell DataType` to manually  overwride the cell `datatype` to `PHPExcel_Cell_DataType::TYPE_STRING`

**Comment by kartik-v** [comment]
Thanks for the update. Can you submit a PR for this?

**Comment by ihipop** [comment]
happy to do that.
I will working on  a  reasonable way to implement this feature

**Comment by kartik-v** [comment]
Resolved via #276
