### ISSUE TITLE
Change 'Export Data - (c) Krajee' title

### ISSUE THREAD

**Issue by iadj** [kartik-v/yii2-export#146]
I feel like the '(c) Krajee' and 'krajee yii2-export plugin' in the browser windows' titles and exported file descriptions are kind of overkill for an open source BSD3 license plugin. Having it in a browser window title isn't good for user experience.

**Comment by kartik-v** [comment]
I do not think it is any issue. You can change them to what you want by changing the respective properties for php excel.
