### ISSUE TITLE
Custom url for download.

### ISSUE THREAD

**Issue by gaganmcp** [kartik-v/yii2-export#147]
Hi Kartik,

When I click on the download button (csv/excel) it goes to the index function for that particular controller. But my grid is rendered from different action. 
So can I pass any url (location) for download so that whenever I click on download it will go to particular url or function not to index?

**Comment by kartik-v** [comment]
Update to release v1.3.4 and then in your other download action - render ExportMenu with `ExportMenu::triggerDownload` set to `true` and `ExportMenu::exportType` set to the specific export type.

**Comment by deferenty** [comment]
Have a similar situation in version 1.4.1

The first grid is loaded from the first action, the second grid loaded via ajax from the second action.

Export from the first grid works excellent, export from the second grid goes to the same action, as the first grid.

If I set `ExportMenu::triggerDownload` to `true` and `ExportMenu::exportType` to `ExportMenu::FORMAT_EXCEL_X` for second grid it is loaded in some strange format, not html.
