### ISSUE TITLE
Define export columns in runtime

### ISSUE THREAD

**Issue by RomeroMsk** [kartik-v/yii2-export#15]
I want to make a form with checkbox list to give user a possibility to chose columns for export. When submitting an export form I need to export only checked columns from POST array.
Is it possible to use your widget in my case?

**Comment by gaurabhi** [comment]
Dear All,
This is What I Want, means I a .csv File with Delimiter "^".  
![image](https://user-images.githubusercontent.com/36297855/37420136-12a4bf5a-27dc-11e8-949d-cbbb92c53bbd.png)

My Index is as 

![image](https://user-images.githubusercontent.com/36297855/37420461-da767244-27dc-11e8-8aa5-5b7cacec51ce.png)
