### ISSUE TITLE
Multiple worksheets in one excel file

### ISSUE THREAD

**Issue by jonatasfl** [kartik-v/yii2-export#152]
There is an easy way to create multiple worksheets in one exported excel file or I need to use PHPExcel directly for this?  

Thank you for this great extension!
Sorry for my bad english.

**Comment by kartik-v** [comment]
You need to use PHPExcel capability for this via this extension... from yii grid perspective there is no direct logic to identify what will be in multiple worksheets...

In case you have a suggestion for enhancement let know via a PR... closing this.
