### ISSUE TITLE
Error: Problems with nested form

### ISSUE THREAD

**Issue by vanvugt13** [kartik-v/yii2-export#166]
I've some problems with a nested form and the ExportMenu functionality in Yii2. I want to use the ExportMenu within a ActiveForm but it doesn't work.

I use the latest version of yii2 (2.0.9) and yii2-export. The browser is Firefox 47.0 on Windows.

**Comment by kartik-v** [comment]
Pls look at your app code.

Nested forms are not allowed in HTML. [Read this](http://stackoverflow.com/questions/555928/is-it-valid-to-have-a-html-form-inside-another-html-form).
