### ISSUE TITLE
HTML tags are replaced even with Raw Format

### ISSUE THREAD

**Issue by KirillRyzhkov** [kartik-v/yii2-export#168]
I set up the column with
```
			[
				'attribute'=>'value',
        		'value' => function ($model) {
        			return Yii::$app->formatter->asRaw($model['value']);
        		},
			],
```
I want to get 
`<span style="font-weight:700;">"{text}"</span>`
But in the export file I get
`&lt;span style=&quot;font-weight:700;&quot;&gt;&quot;{srch_text}&quot;&lt;/span&gt;`
I also tried format => raw, which remove html tags completely.

How to solve this issue?

**Comment by kartik-v** [comment]
Duplicate to #126 and will be addressed via that.
