### ISSUE TITLE
Unable to hide export format options

### ISSUE THREAD

**Issue by shahidt** [kartik-v/yii2-export#169]
## Prerequisites
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-export.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](https://demos.krajee.com/export) and [demos](https://demos.krajee.com/export-demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).
## Steps to reproduce the issue
1. Implement the extension
2. Configure exportConfig option as follows...

```
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $cols,
        'responsive' => true,
        'hover' => true,
        'export' => false,
        'exportConfig' => [
                            'pdf' =>false,
                        ],
    ]); ?>
```
## Expected behavior and actual behavior

In the Export Menu, I expect to not see the option to Export to PDF, but it continues to show the PDF menu.
## Environment

PHP 5.6. Composer updated all extensions and yii2 as on the date of posting this issue.
#### Browsers
- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari
#### Operating System
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile
#### Libraries
- jQuery version: 2.2.4
- yii2-export version: v1.2.5
## Isolating the problem
- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [X] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-export without other plugins.

**Comment by rrhyne** [comment]
I am seeing this issue as well in version v1.2.7. Configuration:


`
<?php
echo ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
    'target' => ExportMenu::TARGET_BLANK,

]);

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel'  => $searchModel,
    'layout'       => "{items}\n{pager}",
    'columns' => $gridColumns,
    'exportConfig' => [
                GridView::CSV => [],
                GridView::HTML => false,
                // do not include PDF
            ],

]); ?>
`

**Comment by NestorAcevedo** [comment]
I am having the same issue. Tested on Firefox Quantum and Chromium.

I have configured exportOptions as following:
```
'exportConfig' => [
                ExportMenu::FORMAT_TEXT => false,
                ExportMenu::FORMAT_PDF => true,
                ExportMenu::FORMAT_HTML => false,
                ExportMenu::FORMAT_EXCEL_X => true,
                ExportMenu::FORMAT_EXCEL => false,
                ExportMenu::FORMAT_CSV => true
            ],
```
But still the default options are rendered.

**Comment by kartik-v** [comment]
Update to the latest release v1.3.4.

And with respect to your setup - JUST SET those formats to `false` which you do not want to displayed.  So just this will work:

```php
exportConfig' => [
    ExportMenu::FORMAT_TEXT => false,
    ExportMenu::FORMAT_HTML => false,
    ExportMenu::FORMAT_EXCEL => false,
],
```

to hide the above formats. 

DO NOT SET `true` values as you have done against the formats. Set `false` to hide, else skip for default setting, or set an array to override default setting.
