### ISSUE TITLE
ToggleData doesn't seem to work for SqlDataProvider

### ISSUE THREAD

**Issue by Mudders** [kartik-v/yii2-export#171]
## Steps to reproduce the issue
1. This is a simplified version
   In the Controller:

```
$query = Entryrecord::find();
$count = Yii::$app->db->createCommand('SELECT COUNT(*) FROM (' . $query->createCommand()->getRawSql() . ') as count_alias')->queryScalar();
$dataProvider = new SqlDataProvider([
    'sql' => $query->createCommand()->getRawSql(), 
    'totalCount' => $count,
    'pagination' => [
              'pageSize' => 10,
        ], 
]);
return $dataProvider;
```

In the View

```
$gridColumns = [
      'id',
      'created_date'
  ];

  echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
    'panel' => [
        'type' => GridView::TYPE_PRIMARY,
        'heading' => 'Records',
    ],
    'pjax' => true,
    'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
    // the toolbar setting is default
    // set a label for default menu
    'export' => [
        'label' => 'Page',
        'fontAwesome' => true,
        'showConfirmAlert' => false,
        'target' => ExportMenu::TARGET_SELF,

    ],
    'exportConfig' => [
      GridView::CSV => [],
      //GridView::PDF => [],
      GridView::EXCEL => [],
    ],
    // your toolbar can include the additional full export menu
    'toolbar' => [
        '{toggleData}',
        '{export}',
    ],
  ]);
```
## Expected behavior and actual behavior

When I follow those steps, I see...
I have 747 records split into pages of 10. When clicking the ToggleData button I see only the first page of records (10) and the pagination button are removed.

I was expecting...
To see all 747 records.
## Environment

Wamp on Windows but the same is happening on the live Ubuntu Server
#### Browsers

all browsers have the same behaviour
#### Operating System
- [X ] Windows
- [ ] Mac OS X
- [ X] Linux
- [ ] Mobile

I can't find an example of using the SqlDataProvider so I am just hoping it is supported?
Or is there an issue in my code?

Thanks.

**Comment by geopamplona** [comment]
i have same problem

**Comment by thealex42** [comment]
same problem here

**Comment by kartik-v** [comment]
Needs to be reported in `yii2-grid` (not part of this extension) - Will need to be handled in that repo.
