### ISSUE TITLE
Undefined variable: dataProvider

### ISSUE THREAD

**Issue by Kakengi** [kartik-v/yii2-export#172]
```
<h1><?= Html::encode($this->title) ?></h1>
<?php // echo $this->render('_search', ['model' => $searchModel]); ?>

<p>
    <?= Html::a('Create Companies', ['create'], ['class' => 'btn btn-success']) ?>
</p>
<?php Pjax::begin(); ?>
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],

       // 'company_id',
        'company_name',
        'company_email:email',
        'company_address',
        'comany_start_date',
```
1. in /var/www/html/advanced/backend/views/companies/index.php at line 24 – yii\base\ErrorHandler::handleError(8, 'Undefined variable: dataProvider', '/var/www/html/advanced/backend/v...', 24, ...)
   18192021222324252627282930
   
   <p>
       <?= Html::a('Create Companies', ['create'], ['class' => 'btn btn-success']) ?>
   </p>
   
   <?php Pjax::begin(); ?>
   <?= GridView::widget([
       'dataProvider' => $dataProvider,
       'filterModel' => $searchModel,
       'columns' => [
           ['class' => 'yii\grid\SerialColumn'],
   
   ```
      // 'company_id',
       'company_name',
   ```

**Comment by metola** [comment]
Maybe you don´t pass the variable from controller.

**Comment by kartik-v** [comment]
This is a coding issue you need to debug in your app. Unfortunately not related to this extension.
