### ISSUE TITLE
Export stopped working from 1.2.5 to 1.2.6

### ISSUE THREAD

**Issue by augustasgiedraitis** [kartik-v/yii2-export#173]
Hello. I am using kartik export widget's exportmenu class to export grid's info. Yesterday I noticed that clicking export does nothing. Tried looking for some javascript errors as it seemed like something related to that. No errors, just nothing happens. Today I changed the version from 1.2.6 to 1.2.5 and it started working again. Perhaps you have a guess what could be causing such a behavior after the update?

**Comment by kartik-v** [comment]
You need to check your yii development app configurations... for example you may need to clean your web assets folder and clear browser cache and restart in case you are updating extensions that contain JS/CSS assets.

**Comment by kartik-v** [comment]
also current release is v1.2.7... closing this...
