### ISSUE TITLE
Hyperlinks in excel exports

### ISSUE THREAD

**Issue by PaulKish** [kartik-v/yii2-export#176]
I have tried setting URLs as part of the grid columns, these are not being recognized by Excel, does the library support this? I can't seem to find examples anywhere

**Comment by PaulKish** [comment]
I was able to get a solution by extending the ExportMenu class and adding the hyperlink using PHPExcel's functions.

**Comment by kartik-v** [comment]
Check with latest release and let know.

**Comment by tlgtrn** [comment]
Could not create clickable links.
I tried 'html', 'url', 'raw' formats for column.
Solved by following:
`[
        'attribute' => 'myAttr',
        'label' => 'myLabel,
        'format' => 'raw',
        'value' => function ($model, $key, $index, $widget) {
                return "=HYPERLINK(\"" . Url::base(true) . Url::toRoute(['media/down', 'id' => $model->myOtherAttr->id]) . "\", \"" . Yii::t('app', 'Download') . "\")";
        }
 ]`
