### ISSUE TITLE
renderAjax issue

### ISSUE THREAD

**Issue by jcaub** [kartik-v/yii2-export#178]
I'm trying to use kartik-v: yii2-export with the module grid through a renderAjax 
But each time i'm trying to do an export (Excel) a new tab is open and my index is reloaded in it but no export is generated. full export works fine on other page with classic render.

[code.txt](https://github.com/kartik-v/yii2-export/files/571312/code.txt)

**Comment by SkyTaurus** [comment]
I have the same problem - the window opens, but nothing happens.

**Comment by almirb** [comment]
I have the same problem too.

**Comment by kartik-v** [comment]
Get the latest release >= v1.3.4.
