### ISSUE TITLE
how to add rows before table ?

### ISSUE THREAD

**Issue by mysoundmagic** [kartik-v/yii2-export#181]
hello,
how to add rows before table with this extension ?
what this extension has the ability to make a row?
like this one :
![test_table](https://cloud.githubusercontent.com/assets/5405947/20837300/14d9a7e8-b8d6-11e6-9295-0483c0a5df4c.png)

**Comment by kartik-v** [comment]
You can use PHPExcel Methods to manipulate your output. Use the various properties starting with `on` to do this. For example set the `onRenderHeaderCell` or `onRenderDataCell` properties as Closures.

Read the [ExportMenu Settings in the docs](http://demos.krajee.com/export#settings).

**Comment by mysoundmagic** [comment]
could you give me an example ?
i was try like this 
```
'onRenderHeaderCell'=>function ($cell, $content, $grid){
	return $cell->setCellValue('A1', 'cell value here'); 
}
```
error :
> Call to undefined method PHPExcel_Cell::setCellValue()
