### ISSUE TITLE
A non-numeric value encountered

### ISSUE THREAD

**Issue by RichWeber** [kartik-v/yii2-export#182]
## Steps to reproduce the issue

1. PHP 7.1

## Expected behavior and actual behavior

When I follow those steps, I see...

```
PHP Warning – yii\base\ErrorException

A non-numeric value encountered

1. in /app/vendor/kartik-v/yii2-export/ExportMenu.php at line 857

     protected function getColumnLabel($key, $column)
    {
        $label = Yii::t('kvexport', 'Column') . ' ' . ($key + 1);
        if (!empty($column->label)) {
            $label = $column->label;
        } elseif (!empty($column->header)) {
            $label = $column->header;
        } elseif (!empty($column->attribute)) {
            $label = $this->getAttributeLabel($column->attribute);
        } elseif (!$column instanceof DataColumn) {
            $class = explode("\\", $column::classname());
            $label = Inflector::camel2words(end($class));
```

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

<img width="1158" alt="2016-12-13 13 36 02" src="https://cloud.githubusercontent.com/assets/1702252/21138933/2382d722-c139-11e6-85df-e59456d05b8e.png">

**Comment by NestorAcevedo** [comment]
I apologize to take again this issue, but I have just tested on AWS getting the same result but in local environment works.

The description is on closed issue #142
