### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focus' of null when exporting

### ISSUE THREAD

**Issue by jeroenk22** [kartik-v/yii2-export#187]
Hi Kartik,

I'm using this widget seperate from your gridview widget because, I don't want a bootstrap styled grid.
So I can't use the panel/toolbar that comes with your gridview.
When I'm trying to configure this export-widget like you did in your demo's, it constantly shows a `JS `error:

![error](https://cloud.githubusercontent.com/assets/3177682/21725205/b050425a-d437-11e6-8869-8a9353c2e01e.png)
![error2](https://cloud.githubusercontent.com/assets/3177682/21725348/5c18eb96-d438-11e6-9886-74ff365ad19c.png)

This kind of error **even shows up in all your demo's** of this widget.

I also can't get the nice confirmation modal. It shows a default `JS` confirm.
Tried to remove `'bootstrap' => false` from the gridview, but that didn't make any difference.

Could you please provide some help?

Thanks in advance!

**Comment by kartik-v** [comment]
On the popup error:

- It is an error specific to your client browser you are testing on. You have to enable popup blocker to allow popups on your browser as CLEARLY MENTIONED IN THE CONFIRMATION DIALOG before upload.

On the pretty confirmation modal dialog:

- you require the kartik-v/yii2-dialog extension to be installed along with `bootstrap`
