### ISSUE TITLE
Example for pdf formatting

### ISSUE THREAD

**Issue by msoa** [kartik-v/yii2-export#189]
I very searched but can not change styles in exported pdf such as font, border & . . .
Can give me an example who can do it?

**Comment by damianobertuna** [comment]
Hi, did you find any solution?

**Comment by msoa** [comment]
> Hi, did you find any solution?
unfortunately no. Due to lack of time i changed my method.

**Comment by kartik-v** [comment]
[Read this comment](https://github.com/kartik-v/yii2-export/issues/220#issuecomment-428900862).
