### ISSUE TITLE
set encoding utf-8 to html file

### ISSUE THREAD

**Issue by dogrocker** [kartik-v/yii2-export#191]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](https://demos.krajee.com/export) and [demos](https://demos.krajee.com/export-demo).

## Steps to reproduce the issue

1.export html file with IE, Edge
2.open
3.there are no encoding at all

## Expected behavior and actual behavior

I was expecting to get `<meta charset="UTF-8">`

#### Browsers
- [x] Internet Explorer
- [x] MS Edge

#### Operating System

- [x] Windows

**Comment by kartik-v** [comment]
It is already configurable and defaulted to `utf-8` via `ExportMenu::$encoding` property.
