### ISSUE TITLE
PDF not generating

### ISSUE THREAD

**Issue by pptyasar** [kartik-v/yii2-export#192]
When using export working all export   except PDF 

Showing as file not found

My version 2324fd5

**Comment by Shold** [comment]
See logs. In my case is a permission denied
`file_put_contents(/path/to/project/vendor/mpdf/mpdf/ttfontdata/dejavusanscondensed.GSUBGPOStables.dat): failed to open stream: Permission denied`

**Comment by pptyasar** [comment]
Its showing as file not found

**Comment by metola** [comment]
Download the last update, try it, and if not solved, put the code here.

**Comment by kartik-v** [comment]
Yes get the latest updated code.
