### ISSUE TITLE
TypeError: $(...).gridexport is not a function

### ISSUE THREAD

**Issue by mohammadhosain** [kartik-v/yii2-export#195]
After pjax this error occurs :
```TypeError: $(...).gridexport is not a function```

**Comment by kartik-v** [comment]
You need to handle the javascript plugin reinitalization for export menu... in case you are overwriting the content yourself with your own PJAX routine... else render the export menu in a separate zone not overwritten by PJAX OR... use renderAjax... to render the ExportMenu based on your design.
