### ISSUE TITLE
onRender- not properly documented

### ISSUE THREAD

**Issue by Kreat1vK0dr** [kartik-v/yii2-export#197]
The following is an excerpt of the onRender- functions:

```
onRenderHeaderCell
Closure, is the callback function that is executed on rendering the header cell output content. The anonymous function should have the following signature:

function ($cell, $content, $grid)
where:

cell: PHPExcel_Cell, is the PHPExcel work sheet object instance

content: string, is the header cell content being rendered

grid: GridView, is the current grid object instance

onRenderDataCell
Closure, is the callback function that is executed on rendering each body data cell output content. The anonymous function should have the following signature:

function ($cell, $content, $model, $key, $index, $grid)
where:

cell: PHPExcel_Cell, is the PHPExcel work sheet object instance

content: string, is the header cell content being rendered

model mixed, is the data model

key mixed, is the key associated with the data model

index integer, is the zero-based index of the data model among the models array returned by GridView::dataProvider

$grid: GridView, is the current grid object instance

onRenderFooterCell
Closure, is the callback function that is executed on rendering the footer cell output content. The anonymous function should have the following signature:

function ($cell, $content, $grid)
where:

cell: PHPExcel_Cell, is the PHPExcel work sheet object instance

content: string, is the footer cell content being rendered

grid: GridView, is the current grid object instance

onRenderSheet
Closure, is the callback function that is executed on rendering the work sheet. The anonymous function should have the following signature:

function ($sheet, $grid)
where:

sheet: PHPExcel_Worksheet, is the PHPExcel work sheet object instance

grid: GridView, is the current grid object instance

```

This does not inform the user what the functions must return. An example of each function's use would also be helpful.

**Comment by kartik-v** [comment]
The functions will not return anything. They just give you access to the PHP Excel objects (e.g. `$cell`, `$sheet` etc.) to customize your PHP Excel output behavior. You may need access the PHP excel docs to get details on using these components.

**Comment by kartik-v** [comment]
I have left this issue open though - for suggestions to improve.

**Comment by Kreat1vK0dr** [comment]
Yes I found some nice resources and was able to get somewhere.

However, how does the export funciton know which export type was selected? For excel I want to remove commas for numeric values, but for pdf I want to keep them (you know, for nice formatting). So in that 'onRenderDataCell' function it would be nice to be able to remove the commas and set the values and data types only when exporting to excel and, say, csv (it being comma separated and all), but to ignore pdf. 

If I can get hold of the export type ('excel', 'csv', or 'pdf') how can I pass that to the 'onRenderDataCell' function?

And a second question - semi-related to this because it deals with rendering - how could I format the pdf file? Currently there is none:

![image](https://cloud.githubusercontent.com/assets/17250286/25373385/c292a9dc-2999-11e7-9034-86c72f3ec450.png)

**Comment by kartik-v** [comment]
You can access it through the `$grid` object... will create a public function `getExportType` for accessing the export type.

**Comment by kartik-v** [comment]
Note that  you can access all public methods of the `ExportMenu` with the `$grid` object within the `onRender` callbacks. For example you can get other object instances as well:

```
// getters
$grid->getPHPExcel(); // returns PHP Excel object instance
$grid->getPHPExcelWriter();  // returns PHP Excel Writer object instance
$grid->getPHPExcelSheet();  // returns PHP Excel Sheet object instance
$grid->getExportType(); // returns the currently selected export type

// you also have setters
$grid->setPHPExcel($obj); // sets/overwrites the PHP Excel object
$grid->setPHPExcelWriter($obj); // sets/overwrites the PHP Excel Writer object
$grid->setPHPExcelSheet($obj); // sets/overwrites the PHP Excel Sheet object
```

**Comment by kartik-v** [comment]
Also have added a separate [On Render Methods](http://demos.krajee.com/export#onrender-methods) section to the docs.

**Comment by Kreat1vK0dr** [comment]
@kartik-v  could you please answer my second question regarding the pdf file formatting?
