### ISSUE TITLE
yii2-export adds malformed krajeeExportGridSalt variable to session

### ISSUE THREAD

**Issue by Kreat1vK0dr** [kartik-v/yii2-export#198]
When I add `ExportMenu::widget` it sets a session variable called `krajeeGridExportSalt` which has malformed data that causes my session in the db to be deleted and as a consequence fires a denyCallback because info that I need in the session for is no longer there.

Here is my session data:

```
__flash|a:0:{}__id|i:1076;adminTenant|s:2:"33";reportDateStart|s:23:"2017-04-01 00:00:00.000";reportDateEnd|s:23:"2017-04-21 14:50:59.999";reportDateDays|i:20;krajeeGridExportSalt|s:32:"����]i�@ſj��g�e���)VN���";
```

How can I prevent your widget from setting session variables without it affecting its functionality (it obviously uses this variable somewhere) ?

**Comment by metola** [comment]
Thats weird.
This session variable get with generateRandomKey(), it see in line 64, in yii2-grid/module:
`$session->set(self::SALT_SESS_KEY, Yii::$app->security->generateRandomKey());`
If you want change, do it, but I don´t think that´s it.
Try it.

**Comment by kartik-v** [comment]
@Kreat1vK0dr firstly this is not related to the ExportMenu .. the variable you mention is part of `yii2-grid` module and you can only experience this if you are using the yii2-grid` module (and its inherent export functionality which is different from `yii2-export`).

The variable is used to store a random session salt for hashing the export data to prevent data tampering when flowing between client and server. 

You can prevent the session data getting created by setting `\kartik\grid\Module::exportEncryptSalt` to a random salt. Refer the grid view [module documentation](http://demos.krajee.com/grid#module) for details.
