### ISSUE TITLE
mime type not correclty set

### ISSUE THREAD

**Issue by Bhoft** [kartik-v/yii2-export#199]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. export some grid needless of type (good to check with target _blank)
2. check the mimetype of the download request repsonse
3. mime type is always text/html; charset=UTF-8

## Expected behavior and actual behavior

Depending of the export type e.g. for excel "application/vnd.ms-excel"
so the browser would suggest to "open with" with the correct application.

btw. your https certificate for the demo pages aren't working or as it looks you have some vhost issue.
see:
https://demos.krajee.com/export-demo

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

#### Libraries

- jQuery version:
- yii2-export version:

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-export without other plugins.

**Comment by kartik-v** [comment]
Not gone through the issue -- but on your other query the demo sites are not on HTTPS...

**Comment by Bhoft** [comment]
but they are linked in your issue template with https ;)
But this was just a remark.

If you look at the pull request you will easily see what was wrong in your code.
I am pretty sure that you want to output a mimetype if its not empty.
