### ISSUE TITLE
Too many problems！

### ISSUE THREAD

**Issue by yoyo0926** [kartik-v/yii2-export#201]
php5.5, + mysql + yii2.0

1、composer after finishing，error:  no find yii2-dialog
2、composer yii2-dialog ,error: requires bower-asset/bootstrap3-dialog ~1.34
3、too tired...

**Comment by yoyo0926** [comment]
Is it possible for developers to integrate resources into one group composer, thanks

**Comment by kartik-v** [comment]
Not clear on what the issue is? The extension has dependencies to other libraries like `yii2-dialog` and these will be installed automatically if you are installing via composer.
