### ISSUE TITLE
Better event listening for dynamic export menu rendering

### ISSUE THREAD

**Issue by Kreat1vK0dr** [kartik-v/yii2-export#204]
## Steps to reproduce the issue

1. Load multiple tables on one page with kartik gridview containing kartik-export.
2. Have each table be in a pjax-container for date range updates etc.
3. Cause the pjax to fire by changing an input
4. Try to download/export a file using the kartik-export widget.

## Expected behavior and actual behavior

When I follow those steps, I see that the new listeners are not bound to the document. The reason is because the new listeners are of the format JQuery("#id") or $("#id") and with the html injection are not put into a $(document).on("ready"...) function. So the event does not fire and the data is not downloaded.

I would expect that you generate your event listeners with at least JQuery(document).on("action", "#id", function(){}) or $(document).on("action", "#id", function(){}) etc rather than JQuery("#id") which would bind the listener to the document if injected with an ajax or pjax request.

Would you be able to implement this ?

#### Browsers

- [x] Google Chrome

#### Operating System
- [Sierra 10.12.1] Mac OS X

#### Libraries

- jQuery version: 2.24
- yii2-export version: 1.2.0

**Comment by botonakis** [comment]
Same problem here.
yii2-export version: 1.2.8
