### ISSUE TITLE
Can't download pdf file

### ISSUE THREAD

**Issue by SnitramDev** [kartik-v/yii2-export#206]
The pdf rendering library 'Mpdf.php' was not found or installed at path

I followed instructions from here:
https://github.com/kartik-v/yii2-export

What's wrong?

**Comment by kartik-v** [comment]
You need to run composer update and ensure you have latest mpdf library 7.x  release

**Comment by SnitramDev** [comment]
Here's my composer, what do I have to change?

  "require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "~2.0.5",
    "yiisoft/yii2-bootstrap": "~2.0.0",
    "yiisoft/yii2-swiftmailer": "~2.0.0",
    "kartik-v/yii2-password": "@dev",
    "dmstr/yii2-adminlte-asset": "2.*",
    "digitv/kint": "1.x-dev",
    "kartik-v/yii2-grid": "@dev",
    "kartik-v/yii2-krajee-base": "@dev",
    "kartik-v/yii2-widgets": "@dev",
    "kartik-v/yii2-mpdf": "@dev",
    "kartik-v/yii2-export": "@dev"
  },
