### ISSUE TITLE
i ran composer update and now am getting Setting unknown property: kartik\export\ExportMenu::streamAfterSave

### ISSUE THREAD

**Issue by preciousgeorge** [kartik-v/yii2-export#212]
## Steps to reproduce the issue

1. Run composer update
2. Refresh web page

## Expected behavior and actual behavior

When I follow those steps, I see 
Setting unknown property: kartik\export\ExportMenu::streamAfterSave

I was expecting

The gridview

**Comment by kartik-v** [comment]
Yes there is a recent BC breaking update as mentioned in #208 - the `streamAfterSave` property is redundant and not required anymore... (you can use the `stream` property to achieve the same) ... the docs and demos will be updated.
