### ISSUE TITLE
Enhance to use PHPSpreadsheet instead of PHPExcel

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-export#213]
Enhance and change extension to use PHPOffice/PHPSpreadsheet instead of PHPOffice/PHPExcel (since PHPExcel will not be supported henceforth).

**Comment by goffyara** [comment]
and this is one reason not to use 7.1 ... Needed...
https://github.com/PHPOffice/PHPExcel/issues/1244#event-1138601124

**Comment by kartik-v** [comment]
Yes... there is unfortunately still not a stable release of PHPSpreadsheet so far... see some issues on tests like Excel 5 export giving bad output... hoping there is some beta release at least.

**Comment by vitorarantes** [comment]
@kartik-v any updates about this ?

**Comment by kartik-v** [comment]
PhpSpreadsheet is still in beta... will need some testing for its first stable release. Will check and see if I get time to implement and test it.

**Comment by kartik-v** [comment]
Resolved via #232.
