### ISSUE TITLE
Menu Export Not Working

### ISSUE THREAD

**Issue by Sakthivelkandasamy** [kartik-v/yii2-export#214]
Yii2 Menu Export Not working i am using on AdminBSB - Material Admin Panel. and I will attached the error  message . please help
![capture](https://user-images.githubusercontent.com/24720919/27983494-eb9a4972-63da-11e7-9d31-755d7c4e57e9.PNG)

**Comment by kartik-v** [comment]
Not related to the extension. You need to check your javascript getting loaded and the sequence. For example the bootstrap modal plugin within `bootstrap.js` must be loaded properly before this and must not be overridden by your other themes and third party JS.

**Comment by Sakthivelkandasamy** [comment]
I am using on materialize.min.js not a bootstrap.js
