### ISSUE TITLE
It does not export to pdf files.

### ISSUE THREAD

**Issue by rodolfopablo** [kartik-v/yii2-export#216]
I want to raise two problems. The first is that I run a SQLDataProvider like this:

$dataProvider = new SqlDataProvider([
'sql' => 'select to_char(fecha,\'dd-mm-yyyy\') as fecha, ventas_bolsa_pesos as ventaspesos, compras_bolsa_pesos as compraspesos, (ventas_bolsa_pesos - compras_bolsa_pesos) as netopesos, ventas_bolsa_kwh as ventaskwh, compras_bolsa_kwh as compraskwh,(ventas_bolsa_kwh - compras_bolsa_kwh) as netokwh from public.it_cliq_xm where fecha >= \'' . $dato1 . '\' and fecha <= \'' . $dato2 . '\' and version = \'' . $version . '\' and agente in (select agente from public.it_agente_in where id_empresa = \'' . $idempresa . '\' and tipo = \'COMERCIALIZADOR\')
 union
 select \'TOTAL\' as fecha, sum(ventas_bolsa_pesos) as ventaspesos, sum(compras_bolsa_pesos) as compraspesos, (sum(ventas_bolsa_pesos - compras_bolsa_pesos)) as netopesos, sum(ventas_bolsa_kwh) as ventaskwh, sum(compras_bolsa_kwh) as compraskwh,sum(ventas_bolsa_kwh - compras_bolsa_kwh) as netokwh from public.it_cliq_xm where fecha >= \'' . $dato1 . '\' and fecha <= \'' . $dato2 . '\' and version = \'' . $version . '\' and agente  in (select agente from public.it_agente_in where id_empresa = \'' . $idempresa . '\' and tipo = \'COMERCIALIZADOR\')  order by fecha asc',
'totalCount' => $j,
'pagination' => [
    'pageSize' => 35,
    'params' => [
    'dato1' => $dato1,
    'dato2' => $dato2,
    'version' => $version,
    'page' => Yii::$app->request->get('page'),
    ],
    ],
]);

But the variable $dato1, $dato2 and $version does not support them since doing the export gives an error in database like this:

Database Exception – yii\db\Exception

SQLSTATE[22007]: Invalid datetime format: 7 ERROR: invalid input syntax for type date: ""
LINE 1: ... as netokwh from public.it_cliq_xm where fecha >= '' and fec...
^
The SQL being executed was: select to_char(fecha,'dd-mm-yyyy') as fecha, ventas_bolsa_pesos as ventaspesos, compras_bolsa_pesos as compraspesos, (ventas_bolsa_pesos - compras_bolsa_pesos) as netopesos, ventas_bolsa_kwh as ventaskwh, compras_bolsa_kwh as compraskwh,(ventas_bolsa_kwh - compras_bolsa_kwh) as netokwh from public.it_cliq_xm where fecha >= '' and fecha <= '' and version = '' and agente in (select agente from public.it_agente_in where id_empresa = '175' and tipo = 'COMERCIALIZADOR')
union
select 'TOTAL' as fecha, sum(ventas_bolsa_pesos) as ventaspesos, sum(compras_bolsa_pesos) as compraspesos, (sum(ventas_bolsa_pesos - compras_bolsa_pesos)) as netopesos, sum(ventas_bolsa_kwh) as ventaskwh, sum(compras_bolsa_kwh) as compraskwh,sum(ventas_bolsa_kwh - compras_bolsa_kwh) as netokwh from public.it_cliq_xm where fecha >= '' and fecha <= '' and version = '' and agente in (select agente from public.it_agente_in where id_empresa = '175' and tipo = 'COMERCIALIZADOR') order by fecha asc;
Error Info: Array
(
    [0] => 22007
    [1] => 7
    [2] => ERROR:  invalid input syntax for type date: ""
LINE 1: ... as netokwh from public.it_cliq_xm where fecha >= '' and fec...
                                                             ^
)
↵
Caused by: PDOException

SQLSTATE[22007]: Invalid datetime format: 7 ERROR: invalid input syntax for type date: ""
LINE 1: ... as netokwh from public.it_cliq_xm where fecha >= '' and fec...
^

in /var/www/html/ENERGIT/vendor/yiisoft/yii2/db/Command.php at line 915

When I send the values ​​to those fixed variables and not from the form it gives an error of this type when I export to PDF in the other formats if it exports well:

Can not access this website

It is possible that the website http://192.168.1.101:82/index.php?r=transacciones%2Fcomprasventasgen%2Fcompvengensuccess&dato1=2017-01-01&dato2=2017-07-19&version=TXF&page=2&per-page=35 is temporarily inactive Or that has definitely moved to another address.
ERR_INVALID_RESPONSE

I need some help from Mr. Kartik or someone who knows, to explain to me what I should do or is a development bug because I have been looking for some useful information or solutions for some months, but I have not got anything, on the other hand, the PDF problem appeared when I updated The ExportMenu because before it worked very well, so I'm suspecting that in this update the export to PDF was poorly built.

I need help, thank you.

**Comment by NestorAcevedo** [comment]
> Invalid datetime format: 7 ERROR: invalid input syntax for type date: ""
LINE 1: ... as netokwh from public.it_cliq_xm where fecha >= '' and fec...

Si en los otros la fecha pasa bien, sí es problema de cómo está enviando el parámetro para generar el PDF. Intente revisar la sintaxis SQL en los otros formatos. Dependiendo del IDE, puede instalar o usar XDebug para entrar en detalle del cómo están yendo los parámetros o cómo queda la sentencia SQL y compararla con la que se genera en la opción PDF.

---
If in the others the date goes ok, is an issue on how is sending the parameter to generate the PDF. Depending of your IDE, you can install and/or use XDebog to enter at detail on how are passing the parameters or how is built the SQL sentence and compare it with the generated in the PDF option.

**Comment by kartik-v** [comment]
Did not understand your issue. But you can update to the latest release and let know.
