### ISSUE TITLE
Export to Excel merge rows

### ISSUE THREAD

**Issue by Maksov** [kartik-v/yii2-export#218]
Hello!

How set settings yii2-export to export excel merge rows?
```
    $gridColumns = [
        ['class' => 'kartik\grid\SerialColumn'],
        [
            'attribute'=>'operation_id',
            'value'=>function ($model, $key, $index, $widget) {
                return $model->operation->name;
            },
            'group'=>true,  // enable grouping
            'groupedRow'=>true,
        ], 
```
But it not working
```
    <?php echo ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
    'fontAwesome' => true,
    'target' => '_blank',
            'exportConfig' => [
                ExportMenu::FORMAT_TEXT => false,
                ExportMenu::FORMAT_PDF => false
            ]
    //'folder' => '@webroot/tmp', // this is default save folder on server
    ])
 ?>
```
But how i understand in code yii2-export there is code, that merge cell! 
```
protected function checkGroupedRow($model, $nextModel, $key, $index)
    {....
protected function checkGroupedRow($model, $nextModel, $key, $index)
    {....
protected function generateGroupedRow($groupFooter, $groupedCol)
    {....
```

**Comment by ishitat** [comment]
I am facing the same issue. Did you find the solution ?

**Comment by Maksov** [comment]
@ishitat, hello. no, i can't.

**Comment by kartik-v** [comment]
Please understand that the `yii2-grid` extension and `yii2-export` are 2 different extensions. 

yii2-export uses PHPSpreadsheet (earlier PHPExcel) external library to render the excel output. The yii2-grid grouping features are more of a javascript addon to display the HTML markup as grouped rows. So in summary your yii2-grid grouping functions has no impact on grid grouping in yii2-export nor will it be understood by PHPSpreadsheet in yii2-export.

You need to use PHPSpreadsheet functionality to merge and group rows within yii2-export (you need to read the PHPSpreadsheet  documentation on how to merge excel rows).

You can call them within one of the callback properties like `ExportMenu;;onRenderDataCell` where you can reformat your excel output.
