### ISSUE TITLE
ExportMenu - Full Export PDF not showing gridlines in output PDF

### ISSUE THREAD

**Issue by tusharugale** [kartik-v/yii2-export#223]
## Steps to reproduce the issue

1. Generate Gridview with dataprovider and gridcolumn 
2. Add ExportMenu widget with desired settings in GridView
3. In view, click on Full Export and click on PDF, it will ask for generate pdf, click ok, it will download PDF file

## Expected behavior and actual behavior

When I follow those steps, I see...
There are no borders or gridlines in generated pdf
I was expecting...
to see column borders or gridlines in generated pdf

**Comment by kartik-v** [comment]
Refer #273.
