### ISSUE TITLE
HTML tags in export

### ISSUE THREAD

**Issue by ninetw** [kartik-v/yii2-export#224]
Hi kartik!
I've got some columns with html tags on header. Like this:
[ 'header' => '`<div class="tooltip-advanced"><div class="text-danger"><i class="pe-7s-less fa-lg"></i></div><span class="tooltiptext">Canceled</span></div>`',
            'format' => 'html',
            'value' => function ($data) {
                return '`<div class="pull-right">' . ($data["requests_reflected"]) . '</div>`';
            },
            'footer' => '`<div class="pull-right">' . $searchModel::$amountRequestsReflected . '</div>`'
]
in exported file (excel) I got this header: 
[https://drive.google.com/file/d/0B70mvRBjruFUXzdoVjRTaHZqOVk/view?usp=sharing](url)
How can I fix it? Thanx:)

**Comment by kartik-v** [comment]
Correct your column `header` to show only HTML stripped content n the `ExportMenu` columns configuration.

You can have the column `header` in `GridView` to show the HTML formatted output.
