### ISSUE TITLE
Don't want to export HTML code

### ISSUE THREAD

**Issue by isabelrst** [kartik-v/yii2-export#226]
Hello.

Since the last update when I export any page, columns with HTML code are exported with raw HTML code. I mean, before, if a have a code with `<a href="blababla">Web</a>` the exported file contains "Web" but now contains the full html code  `<a href="blababla">Web</a>` .

I can't find any solution to fix this.

Any suggestions??

Thanks!!

**Comment by kidzen** [comment]
valid...i face the same issue

**Comment by isabelrst** [comment]
@kidzen the only solution that I have found is format row as "number":

```
                                $gridColumns = [
                                    [
                                        'label' => Yii::t('app', 'User'),
                                        'attribute' => 'user_email',
                                        **'format' => 'number',**
                                        'content' => function ($data) {
                                            return Html::a($data->user->email,
                                                ['/user/view', 'id' => $data->user_id],
                                                ['title' => Yii::t('app', 'View User'), 'target' => '_blank']);
                                        },
                                        'filter' => false,
                                    ],
```

**Comment by kartik-v** [comment]
Yes set your column format as supported by Yii formatter to display it as per your need... by default it displays with `format = 'raw'` ... which will display the raw data as is expected.
