### ISSUE TITLE
Cannot get grouped header rows in Excel file

### ISSUE THREAD

**Issue by phiurs** [kartik-v/yii2-export#227]
I have been trying to export data with grouped header rows using Export Menu. I put
```php
'group'=>true, 
'groupedRow'=>true,  
```
in the attribute parameters, but I don't see grouped rows in the exported Excel file.  
I thought this might not be supported, but I've seen it working in this example (where the button is embedded in the GridView):
http://demos.krajee.com/group-grid-demo/3 

I cannot use a GridView with the embedded button because I have to export different, more detailed data than those I show in the grid.

**Comment by kartik-v** [comment]
`yii2-export` uses PHPExcel library to render the excel or other exported output. You need to use PHPExcel properties for formatting your output - as this extension by default uses basic table / grid conversions only.

**Comment by kartik-v** [comment]
In case you have any suggestion to enhance this using PHPExcel in an easy extensible way - do let know.

**Comment by mgrabow1** [comment]
@kartik-v may you please post the contents of `ExportMenu::onRenderDataCell` from you group-grid-demo 3 as an example of a bit more complex case?
I guess it involves adding a row, merging cells and then removing a column - it seems doable, but it would surely be nice to see a real working exaple of it from your code.
