### ISSUE TITLE
Enhancement: Make container optional

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-export#228]
Just a very small feature request.

Could you make it possible to set [`$container`](https://github.com/kartik-v/yii2-export/blob/42fd901373f03dd983481b8fb2ce537e6fa0577e/ExportMenu.php#L209) to `false`, meaning it would not render any container at all?

Like so:

    return $this->container === false ? $content : Html::tag('div', $content, $this->container);

This is useful for example when rendering the export menu inside a custom external button group.

**Comment by kartik-v** [comment]
You should be able to set the CSS class within `ExportMenu::container` to style as per your need - is there an issue with this approach?

**Comment by vercotux** [comment]
Yes, the issue is with Bootstrap which requires a specific HTML layout (for rendering button groups for example). It would require changing Bootstrap CSS to overcome this.

**Comment by OceansCrashing** [comment]
Why not override the bootstrap css, you wouldn't need to change bootstrap
css

On Feb 18, 2018, at 5:52 AM, vercotux <notifications@github.com> wrote:

Yes, the issue is with Bootstrap which requires a specific HTML layout (for
rendering button groups for example). It would require changing Bootstrap
CSS to overcome this.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kartik-v/yii2-export/issues/228#issuecomment-366507517>,
or mute the thread

**Comment by vercotux** [comment]
There is a good reason why bootstrap requires a specific HTML layout. I'd rather not reinvent the wheel. And besides, going through all the effort of overriding bootstrap just to overcome something that could easily be fixed by changing 6 characters makes no sense. It would be far wiser to simply fork this project and avoid unnecessary hacks.

**Comment by OceansCrashing** [comment]
All the effort of overriding bootstrap is precisely what you’re supposed to do with all your css. Anything that bootstrap doesn’t care for, or that you’d like to override, you do in your own css files. This is basic design, and why css is designed with priorities the way it is (the “C” in “CSS”) There’s nothing you can’t do here; you can easily extend this plugin if you want to do things the way you’re looking to do, but a simple CSS edit seems the quickest and best way to skin this cat.

**Comment by vercotux** [comment]
I've resolved this issue by forking yii2-export and correcting the layout. No need for any bootstrap hacks.

**Comment by OceansCrashing** [comment]
Once again, my suggestion was not an “ugly bootstrap hack.” This is how (cascading) css and basic web design work. Sorry you don’t seem to understand that or are chosing to ignore or comment on that

**Comment by vercotux** [comment]
This bug report is about fixing yii2-export. I have made it clear am not interested in unnecessary workarounds.

**Comment by OceansCrashing** [comment]
As is evident by the thread, there is nothing actually broken except your understanding of bootstrap, css, and html. Glad you got a solution you’re happy with

**Comment by vercotux** [comment]
I have good reasons not to select your proposed workaround, so please keep the baseless accusations to yourself, unless you actually have anything constructive to add.

**Comment by OceansCrashing** [comment]
I’m not accusing anything. I asked questions and tried to conduct a normal technical discussion, and you called my proposed solution a hack instead of engaging in an intelligent conversation.

**Comment by vercotux** [comment]
You start with "I'm not accusing anything" and then in the same post you accuse me of "not understanding css". How petty.
I told you that your "solution" is insufficient in my case and likely many others. I don't owe you anything because there is simply no need for me to discuss workarounds that are completely useless in my case, especially after I have already implemented a far better solution. It may not have been "broken" but in my case it might as well be since it was missing a critical feature, which is what this issue is all about. Your proposal does nothing to resolve this and I see no point discussing it. Even if I implement it, yii2-export would still be missing this feature. It would help if you actually read the title.

**Comment by OceansCrashing** [comment]
I read the title, and you still have failed to mention precisely why you wanted no container. You said bootstrap requires a specific html layout which for the most part is simply inaccurate; If that were true it would be largely unusable for most people.  It’s nice that you have a solution, but you should seriously consider providing more detail and explanation so you can receive better support, and out of respect for those who take their time looking out for issues and trying to help. My frustration came from your unwillingness to engage on a technical level, and your offhand dismissal with no reasonable explanation as to why the solution didn’t work. I still don’t think an explanation exists. An empty container should be fine. Works well enough for me in all the projects I’ve used this plugin.

**Comment by vercotux** [comment]
You are entitled to your opinions. Great that it works "well enough for you".
