### ISSUE TITLE
Bug: Exporting shows html tags (e.g. Serial Column)

### ISSUE THREAD

**Issue by 1Luc1** [kartik-v/yii2-export#230]
I guess, after new update, it seems a problem with the export menu. Go to [http://demos.krajee.com/export-demo-dtl/columns-selector-1](http://demos.krajee.com/export-demo-dtl/columns-selector-1) and select export to pdf. The result shows for the serial column the td tags or for the author column the a tag...

[grid-export (5).pdf](https://github.com/kartik-v/yii2-export/files/1567821/grid-export.5.pdf)

**Comment by NestorAcevedo** [comment]
On Excel happens the same.

**Comment by Gil707** [comment]
Seems i had this problem too, how i can export the data as I can see in view...?

**Comment by kartik-v** [comment]
Refer #126.. you need to set the `format` property - else it is treated as `raw`.

**Comment by 1Luc1** [comment]
Thanks for the reply. The demo mentioned above, still doesn't work as expected; unless you want to show the html tags within the export.

Besides that, the bug still exists for kartik\grid\SerialColumn; even with the _format property_ hint.

**Comment by kartik-v** [comment]
Ok this is related to #168 as well... and it is because PHP Excel / PHP Spreadsheet does not do HTML format conversion .... and considers each text as string. I will provide an enhancement shortly.

**Comment by kartik-v** [comment]
This is fixed now,
