### ISSUE TITLE
Kartik gridview export button style.

### ISSUE THREAD

**Issue by PaheerathanSelvarasa** [kartik-v/yii2-export#231]
`use yii\grid\GridView;`
`use kartik\export\ExportMenu;`

`echo ExportMenu::widget([`
          `'dataProvider' => $dataProvider,`
         ` 'columns' => $gridColumns,`
          `'dropdownOptions' => [`
             ` 'label' => 'Export',`
             ` 'class' => 'btn btn-primary'`
       `   ],`
        `  'columnSelectorOptions' => [],`
         ` 'showColumnSelector' => \FALSE,`
         ` 'formatter' => [`
             ` 'class' => 'yii\i18n\Formatter',`
             ` 'nullDisplay' => ' ',`
        `  ],`
          `'exportConfig' => [`
             ` ExportMenu::FORMAT_HTML => false,`
             ` ExportMenu::FORMAT_TEXT => false,`
              `ExportMenu::FORMAT_EXCEL => false,`
        `  ],`
        `  'filename' => 'Documents',`
      `  ]);`
There are two down arrows appeared in Kartik gridview export button. How to remove one down arrow in the export button?
Is there any styling features available?

![screenshot 221](https://user-images.githubusercontent.com/29100886/34480328-c1a94dce-efd1-11e7-9753-ec98511eadd9.png)

**Comment by kartik-v** [comment]
This is controlled by bootstrap dropdown version you are using... CHECK!
