### ISSUE TITLE
Package phpoffice/phpexcel is abandoned

### ISSUE THREAD

**Issue by double-v** [kartik-v/yii2-export#242]
Hi Kartik ! 1st : ty for your work ;)

just to say that composer give me this message :

Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.

Cheers

**Comment by kartik-v** [comment]
The extension already is upgraded some time back and is now in v1.2.8 where the dependency has been set to PHP spreadsheet. You may need to check your app install config.

**Comment by sreenadh** [comment]
@kartik-v  v1.2.8 depends on phpexcel, not phpspreadsheet.

**Comment by kartik-v** [comment]
Use v1.2.9
