### ISSUE TITLE
Set Landscape or Portrait

### ISSUE THREAD

**Issue by neoacevedo** [kartik-v/yii2-export#243]
How do I configure landscape or portrait mode for PDF? I don't figure any mode to achieve it.

**Comment by kartik-v** [comment]
```php
echo ExportMenu::widget([
    'exportConfig' => [
        ExportMenu::FORMAT_PDF` => [
               'pdfConfig' => [] //set mpdf properties here
        ]
    ]
]);
```

**Comment by mkraibt** [comment]
I tried 
`   'exportConfig' => [
                    ExportMenu::FORMAT_EXCEL => false,
                    ExportMenu::FORMAT_PDF => [
                        'pdfConfig' => [
                           'mode' => 'utf-8',
                            'format' => 'A4-L',
                            'orientation' => 'L'
                        ],
                    ],
                ],`
But still comes portrait. Not sure why it won't take the setting.
