### ISSUE TITLE
kvexpmenu_c991377a is not defined

### ISSUE THREAD

**Issue by saranvarma** [kartik-v/yii2-export#245]
Iam getting kvexpmenu_c991377a is not defined while loading the page.iam unable to export the data.

This is the error message from console

ReferenceError: kvexpmenu_c991377a is not defined[Learn More]  index:1299:32
	<anonymous> https://localhost/v2/reports/index#:1299:32
	mightThrow https://localhost/v2/assets/441539b4/jquery.js:3583:21
	resolve/</process< https://localhost/v2/assets/441539b4/jquery.js:3651:12

there is no assets folder in v2. why it is loading from that folder?

**Comment by kartik-v** [comment]
Not related to this extension - check your Yii2 Configuration and Yii2 Asset Manager config.
