### ISSUE TITLE
contentBefore problem

### ISSUE THREAD

**Issue by nazakar** [kartik-v/yii2-export#246]
Hi my code is - no value TEST is showing - only 2 empty rows
'contentBefore' => [
                    'value' => ['TEST'],
                  'styleOptions' => [
                       'font' => [
                         'bold' => true,
                         'color' => [
                        'argb' => '00000000',
                                         ],
                                      ],
                                ],
                       ],

**Comment by thanhbinh0995** [comment]
Try this
'contentBefore' => [
    [
            'value' => 'Test',
    ]
],

**Comment by AngelThomasTinoPoot** [comment]
que tal, como puedo hacer que el titulo salga centrado y en negrita
