### ISSUE TITLE
kartik\export\ExportMenu and kartik\base\TranslationTrait define the same property ($_msgCat) 

### ISSUE THREAD

**Issue by Baha2Odeh** [kartik-v/yii2-export#258]
kartik\export\ExportMenu and kartik\base\TranslationTrait define the same property ($_msgCat) in the composition of kartik\export\ExportMenu. However, the definition differs and is considered incompatible. Class was composed

**Comment by kartik-v** [comment]
You have outdated dependencies or installing extensions manually. Instead auto update your extensions via composer to latest release to get all dependencies also updated.

**Comment by kidzen** [comment]
i get the same also..
already updated...but the error still persist..
try on newly installed yii with dynagrid, the same error pop out..

what i did temporarily to fix it is commenting msgCat from ExportMenu Class..
```
class ExportMenu extends GridView
{
    use TranslationTrait;
    ....
    /**
     * @var string translation message file category name for i18n
     */
    // protected $_msgCat = 'kvexport';
    protected $_msgCat = '';
```

**Comment by kartik-v** [comment]
@kidzen you should not need to modify source code of extensions - you definitely seem to have an outdated version of yii2-export. Cross check the `yii2-export` extension version you have installed on your app versus the `yii2-export` extension and `ExportMenu` version in this repo and you will understand your issue.

**Comment by Lordfef** [comment]
after composer update:

kartik\export\ExportMenu and kartik\base\TranslationTrait define the same property ($i18n) in the composition of kartik\export\ExportMenu. However, the definition differs and is considered incompatible. Class was composed

In my composer.json i have these extensions:
...
        "kartik-v/yii2-datecontrol": "dev-master",
        "kartik-v/yii2-detail-view": "*",
        "kartik-v/yii2-editable": "@dev",
        "kartik-v/yii2-export": "@dev",
        "kartik-v/yii2-grid": "@dev",
        "kartik-v/yii2-password": "@dev",
        "kartik-v/yii2-widgets": "dev-master",
        "kartik-v/yii2-widget-select2": "@dev",
...

I update my composer
removed all kartik extension from composer.json and run composer install
i repast kartik extension and run composer install again but the problem persist

what i'm missing
Thank's

**Comment by droidfanat** [comment]
Made a temporary crutch

edit:  vendor\kartik-v\yii2-export\ExportMenu.php  

delete string " protected  $_msgCat = 'kvexport'; "

And extend construct function.

 public function __construct(array $config = [])
    {
        $this->_msgCat = 'kvexport';
        parent::__construct($config);
    }

**Comment by kartik-v** [comment]
The line of code `protected $_msgCat = 'kvexport'; ` does not exist in ExportMenu.php ... Seems you are working with outdated release of the extension.

**Comment by Lordfef** [comment]
If can be useful, i solve upgrading php from 5.6 to 7.1

**Comment by abdulmanan7** [comment]
I did everything but each time the older version of export got install then I inspect and I was missing PHP zip extension installed it and then composer clear cache and composer update and it's done.

**Comment by virajkadam** [comment]
I tried every way but the same error persisted. Then as per the above comment by @abdulmanan7 . I performed actions as below.

> php --ini

Found out 2 things here.
-- php cli path. (mine was `/etc/php/7.2/cli/conf.d/` ) 
-- And wether **PHP Zip extension** is installed on not. If not installed it by `sudo apt-get install php7.2-zip`

> sudo service apache2 restart

Reflect PHP extension updations to apache.

> sudo phpenmod zip
>sudo service apache2 restart

>composer clearcache

Clear caches of composer

> sudo rm -rf ~/.composer

Just to be safe, even after removing cache files. Removed cache directory itself.

> rm -rf vendor/

Just remove vendor directory just to be sure you don't miss a step. As my composer is up to date and stable. **Think twice about doing so.**

> rm -rf composer.lock

Again, Just to be sure. **Think twice about doing so.**

> composer update

Update extensions with this command.

VOILA!!! Its starts running just like a charm.

**Comment by gpf1993** [comment]
i uprade php5.6  to PHP 7.0.22,   it has wrong, please help  me!!!!  

        "kartik-v/yii2-dynagrid": "@dev",
        "kartik-v/yii2-detail-view": "*",
        "kartik-v/yii2-date-range": "*",
        "kartik-v/yii2-widget-datepicker": "*",
        "kartik-v/yii2-widget-datetimepicker": "^1.4",
        "kartik-v/yii2-export": "dev-master",
        "kartik-v/yii2-mpdf": "^1.0",
        "pjkui/kindeditor": "dev-master",
        "kartik-v/yii2-field-range": "*",
        "kartik-v/yii2-widget-fileinput": "@dev",
        "kartik-v/yii2-tree-manager": "@dev",

**Comment by ZerocoolVishal** [comment]
I also faced the same issue, Use the following
`"kartik-v/yii2-export": "dev-master"`

Don't use:
`"kartik-v/yii2-export": "@dev"`

**Comment by AdiPathak97** [comment]
This issue is still present despite updating dependencies via composer automatically. Requesting a re-open.

**Comment by victormatuk** [comment]
> Made a temporary crutch
> 
> edit: vendor\kartik-v\yii2-export\ExportMenu.php
> 
> delete string " protected $_msgCat = 'kvexport'; "
> 
> And extend construct function.
> 
> public function __construct(array $config = []) { $this->_msgCat = 'kvexport'; parent::__construct($config); }

This one helped me
