### ISSUE TITLE
First line of exports shows a <div> tag

### ISSUE THREAD

**Issue by gb5256** [kartik-v/yii2-export#259]
I am rendering two tabs, each one contains one grid.
The export (any format) will show a `<div>` in the first line.
If I remove the tabs and just show one grid, all works fine.

any ideas?

thanks,
gb5256

**Comment by kartik-v** [comment]
Need to check your HTML markup and Javascript code - if it is throwing some errors on your browser console - which maybe causing some invalid markup.
