### ISSUE TITLE
Ability to configure explicit cell formats (header, footer, content, before, after)

### ISSUE THREAD

**Issue by alexgivi** [kartik-v/yii2-export#276]
on import to .csv format, I found a bug, discussed here:
https://www.sitepoint.com/community/t/exporting-csv-file-large-numbers-being-converted-to-exponent-format/24894

long integer numbers (IMEI in my case) - are converted to exponential form, and it is wrong behaviour.

I found a way to get around the bug: to set cell value explicitly with string format.
this is the code:
```php
            'onRenderDataCell' => function ($cell, $content) {
                /** @var \PhpOffice\PhpSpreadsheet\Cell\Cell $cell */
                $cell->setValueExplicit($content, DataType::TYPE_STRING);
            }
```
but it is a crutch.

I suggest you to add some configuration option, for example 'explicitCellsFormat',
and set the value explicitly with this format, to avoid this problem.
or, I think, it is possible to simply change code of `generateRow` method, because all necessary formatting is performed before, and just set value as a text... but it is actual only for .csv format.
Maybe you should add some option, like 'setCellsAsText', or so on, to add possibility of setting previously formatted values  as is.

Also, maybe I've missed some way to solve this problem? maybe some configuration already exists?

**Comment by kartik-v** [comment]
New enhancement to configure explicit cell formats (header, footer, content, before, after).   Explicit cell formats must be one of the `PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_` constants.  This can be set via `cellFormat` settings at one or more of the following levels. 
   -  `Column::headerOptions['cellFormat']`
   -  `Column::contentOptions['cellFormat']`
   -  `Column::footerOptions['cellFormat']`
   -  `ExportMenu::contentBefore['cellFormat']`
   -  `ExportMenu::contentAfter['cellFormat']`

**Comment by kartik-v** [comment]
Updated demo to [include an example for explicit cell formats](http://demos.krajee.com/export-demo-dtl/explicit-cell-formats).
