### ISSUE TITLE
The export function not working since version 1.3.3

### ISSUE THREAD

**Issue by ahmadhattab** [kartik-v/yii2-export#278]
The module didn't download any file since version 1.3.3, it's stuck on the "Generating the export file. Please wait..." screen without download any file.

**Comment by kartik-v** [comment]
It seems to be a caching problem on your environment. You need to check and clean up your browser cache, and restart and also clean your yii2 runtime web assets on the web server and restart/retry.

The export works fine on the demo pages.

**Comment by RichWeber** [comment]
Hello @kartik-v ,

I have the same problem.

I tried releases from `1.3.6` to `1.3.3`. The export doesn't work.

All work fine only with `1.3.2`

**Comment by RichWeber** [comment]
and a small note after my tries: `'showConfirmAlert' => false` doesn't work, I always see a confirmation alert window

**Comment by RichWeber** [comment]
@ahmadhattab do you use `dmstr/yii2-adminlte-asset`?

Because it's OK on my frontend application, the problem is only on the backend with `dmstr/yii2-adminlte-asset` extension.

**Comment by kartik-v** [comment]
@Richweber it seems to be a problem with outdated and stale JS code running on your client. Clean up runtime web assets and browser cache and restart browser after updating the extension. Clicking SHIFT+refresh on Chrome should hard refresh the cache. You can cross check the same on demos page where the code runs fine.
