### ISSUE TITLE
Exception error when showColumnSelector is false

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-export#284]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Load the page with ExportMenu widget
2. 
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

PHP Warning – yii\base\ErrorException
in_array() expects parameter 2 to be array, null given
in /var/www/xxxxx/vendor/kartik-v/yii2-export/src/ExportMenu.php at line 1227

If showConfirmSelector => true, page is loaded.

I was expecting...

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-export version: V1.3.7

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-export without other plugins.

**Comment by 1Luc1** [comment]
I have the exact same problem. The following worked for me as workaround:
> If showConfirmSelector => true, page is loaded.

**Comment by cluwong** [comment]
Downloaded dev-master version and it works! Thanks for the fix. 
When will this be released as stable version?
