### ISSUE TITLE
ExportMenu selectedColumns warning

### ISSUE THREAD

**Issue by afortiexchange** [kartik-v/yii2-export#286]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Run ExportMenu widget
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

Warning
in_array() expects parameter 2 to be array, null given
1227 $isNoExport = in_array($key, $this->noExportColumns) || !in_array($key, $this->selectedColumns);

I was expecting...

See working widget. ;-)
I suppose default value for $selectedColumns property in kartik\export\ExportMenu shoukd be empty array.

vendor/kartik-v/yii2-export/src/ExportMenu.php:256
public $selectedColumns = [];

## Environment
php 7.2.7-1+0~20180622080852.23+jessie~1.gbpfd8e2e
Linux vbox 3.16.0-5-686-pae #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) i686 
--

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-export version: v1.3.7

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [
![screenshot_1](https://user-images.githubusercontent.com/44020090/48759659-1ec7c380-eca4-11e8-98b0-23d4a88eb8c3.png)
 ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-export without other plugins.

**Comment by kartik-v** [comment]
Duplicate to and resolved via #284.
