### ISSUE TITLE
Empty results when asDropdown is false

### ISSUE THREAD

**Issue by esaesa** [kartik-v/yii2-export#288]
The result is always empty when asDropdown = false.
This is the same in the demo http://demos.krajee.com/export-demo-dtl/custom-menu-list 
## Prerequisites

- [ Y] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [] The issue still exists against the latest `master` branch of yii2-export.
- [Y] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [ Y] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ Y] I have attempted to find the simplest possible steps to reproduce the issue.
- [N ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ x] Mobile

#### Libraries

- jQuery version:
- yii2-export version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-export without other plugins.

**Comment by juliardi** [comment]
This happens to me too. I'm using yii2-export v1.3.8. 
I don't know if this is a typo, but on commit 334e7fe6f27fd4201da8f97f5d85f031b403a257 the message says `Updates to release v1.3.8 fixes #288`, should it be `v1.3.9` ?
