### ISSUE TITLE
Unable to use dynagrid and dynagridOptions to select columns

### ISSUE THREAD

**Issue by arturoliveira** [kartik-v/yii2-export#290]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-export.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Define an export menu and assign it to a variable
2. Use the export menu variable in a DynaGrid

## Expected behavior and actual behavior

When I follow those steps, I see...
An error stating that columns index is not defined

I was expecting...
A DynaGrid to select columns

#### Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Mobile

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-export without other plugins.

**Comment by Sereja3578** [comment]
Have the same problem(
