### ISSUE TITLE
PHP Fatal Error while Create model via instance method

### ISSUE THREAD

**Issue by akramrana** [kartik-v/yii2-export#307]
##  (enh #296) causes PHP Fatal Error – yii\base\ErrorException 

- (enh #296): Create model via instance method line `$model = $modelClass::instance();`

## Environment
Apache 2.4.6 and PHP 5.6

**Comment by milad-ghiami** [comment]
this code has error 
`
            $modelClass =new  $provider->query->modelClass;
           $model = $modelClass::instance();
`

![image](https://user-images.githubusercontent.com/10231350/67791395-9b564b00-fa8c-11e9-9f0e-a98deaea7564.png)
