### ISSUE TITLE
How to export all rows?

### ISSUE THREAD

**Issue by likman** [kartik-v/yii2-export#311]
Hello. I use Export widget with SqlDataProvider with pagination and I need to export all rows. Now widget allows me to export only one page. 

Here is my code:

     $dataProvider = new SqlDataProvider([
            'sql' => $sql,
            'params' => $params,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 100,
            ],
            'sort' => [
                'attributes' => $this->attributes(),
            ],
        ]);

Widget code:

     <?= 'Экспорт: '.ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $searchModel->getColumns(),
    ]);?>

I searched the solution in ExportMenu.php file of the widget and found this code in iniExport() function:

     if ($this->batchSize && $this->_provider->pagination) {
            /** @noinspection PhpUndefinedFieldInspection */
            $this->_provider->pagination = clone($this->dataProvider->pagination);
            $this->_provider->pagination->pageSize = $this->batchSize;
        } else {
            $this->_provider->pagination = false;
        }
If I disable ELSE block, code works perfectly and widget exports all rows. I tried to set "batchSize" parameter, but nothing happend. If batchSize is more than real pageSize of dataProdider, one page exports anyway. 
So what is a good way for export all rows without disabling that code?

**Comment by sihar** [comment]
I try to help
leave ExportMenu.php file original and set your dataprovider parameter like this
```php
    $dataProviderA = new SqlDataProvider([
        'sql' => "select * from your_table",
        'params' => "",
        'totalCount' => total_of_your_data_rows,
        'pagination' => [
            'pageSize' => 10,
            'page' =>your_expected_page_start_from_zero,
        ],
    ]);
```

**Comment by ThreepE0** [comment]
You can set pagination to false IF the app export parameter is set in your controller.  This way filtering still works. I’ll post an example in a couple hours when I get to my computer. 

If you do a var_dump on get and post variables it should become pretty apparent what to do

**Comment by ThreepE0** [comment]
In controller before render:
if(isset($_POST['export_type'])){$dataprovider->pagination = false;}

This will allow you to keep your filters

**Comment by ThreepE0** [comment]
> I try to help
> leave ExportMenu.php file original and set your dataprovider parameter like this
> 
> ```
>     $dataProviderA = new SqlDataProvider([
>         'sql' => "select * from your_table",
>         'params' => "",
>         'totalCount' => total_of_your_data_rows,
>         'pagination' => [
>             'pageSize' => 10,
>             'page' =>your_expected_page_start_from_zero,
>         ],
>     ]);
> ```

There are a few drawbacks to this solution;  It's only useful for dumping the entire table, and it doesn't allow for relations, it doesn't allow for exporting the result of a search, and it requires defining an all-new data-provider.  Better to just disable pagination before filtering and before rendering.

**Comment by sihar** [comment]
Can you give example for what you mean? I think with different approach will give broader insight for us and others.

**Comment by ThreepE0** [comment]
> Can you give example for what you mean? I think with different approach will give broader insight for us and others.

Not sure what you mean here. Have you tried putting the line I included just before your render in your controller action?

**Comment by aikon2** [comment]
`$dataProvider = new SqlDataProvider([
        'sql' => $sql,
        'params' => $params,
        'totalCount' => $count,
        **'pagination' => false,**
         'attributes' => $this->attributes(),
        ],
    ]);`

**Comment by sihar** [comment]
Sorry, seems I only focus to leave ExportMenu.php original for issue that posted.
Thanks for @ThreepE0 and @aikon2 for example script.
I test it and it works

**Comment by sihar** [comment]
I suggest this issue closed
