### ISSUE TITLE
Extension does not show columns since last update

### ISSUE THREAD

**Issue by jeslava** [kartik-v/yii2-export#320]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-export.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.  Open Columns button to select columns
2.
3.

## Expected behavior and actual behavior
Since now I could see the columns and select the columns and now I can't see nothing.

When I follow those steps, I see...

I was expecting...

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [x] Internet Explorer
- [X] Safari

#### Operating System

- [X] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-export version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [X] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-export without other plugins.

**Comment by jeslava** [comment]
<img width="247" alt="Captura de pantalla 2020-03-19 a las 9 17 05" src="https://user-images.githubusercontent.com/4816044/77053613-e38bf080-69ce-11ea-98fa-c87a376af6ba.png">

**Comment by jeslava** [comment]
Downgrading to version 1.4.0 works fine. See attached image.

<img width="243" alt="Captura de pantalla 2020-03-19 a las 12 30 59" src="https://user-images.githubusercontent.com/4816044/77063235-a418d080-69dd-11ea-86d3-612c71181ac5.png">

**Comment by kartik-v** [comment]
Cross check the latest version is updated via composer update. 

It seems your environment has outdated web assets / stale cache - you need to clean your web runtime assets and also the browser cache and hard refresh browsers and retry. You can check that the updated version works fine on the demo site. Cross check the [basic demo example here](https://demos.krajee.com/export-demo-dtl/grid-basic).
