### ISSUE TITLE
ExportWriterPdf::save($pFilename) must be compatible with PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf::save($pFilename): void

### ISSUE THREAD

**Issue by karataserkan** [kartik-v/yii2-export#322]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. open Download dropdown and click Pdf button
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see a PHP Compile Error – yii\base\ErrorException
`Declaration of kartik\export\ExportWriterPdf::save($pFilename) must be compatible with PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf::save($pFilename): void`

I was expecting to download pdf file.
PhpSpreadsheet uses void return and so ExportWriterPdf is not compatible with latest PhpSpreadsheet.
https://github.com/PHPOffice/PhpSpreadsheet/commit/fcd9f10663c5be8e435fd0f92c077a8d8747ded1#diff-8b6c0c683d533f32b31ce28cee1bd3e6R229

https://github.com/PHPOffice/PhpSpreadsheet/commit/fcd9f10663c5be8e435fd0f92c077a8d8747ded1#diff-ac73033eeb17a3b443c4bf75a64d0e18R27

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-export version: @dev

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-export without other plugins.

**Comment by favourkiiza** [comment]
Experiencing the same issue

**Comment by kartik-v** [comment]
resolved via #323
