### ISSUE TITLE
Closure for contentOptions not acceptable

### ISSUE THREAD

**Issue by bscheshirwork** [kartik-v/yii2-export#328]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. use closure for 'contentOptions' of column
```
        'contentOptions' => function ($model) {
            return [
                'class' => 'text-break',
                'data-toggle' => 'tooltip',
                'data-placement' => 'top',
                'title' => someFunctionalForGenerateTitle($model),
            ];
        },

```
2. click download btn
3. have error in 
vendor/kartik-v/yii2-export/src/ExportMenu.php:1394

## Expected behavior and actual behavior

When I follow those steps, I see...
Error

I was expecting...
pick `class` from closure result

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-export version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-export without other plugins.

**Comment by kartik-v** [comment]
Fixed via #329.
