### ISSUE TITLE
Проблема с русской кодировкой при выгрузке в excel 

### ISSUE THREAD

**Issue by hotenot** [kartik-v/yii2-export#331]
Приветствую у сановил расширение все работает отлично но при выгрузке в ексель и попытке открыть пишет что файл поврежден. При открытии в опен офис видно что кодировка не верная. Подскажите плиз что делать

**Comment by bscheshirwork** [comment]
Дважды проверить в какой кодировке передаются данные и какая кодировка стоит на файлах проекта
