### ISSUE TITLE
Change export url or action

### ISSUE THREAD

**Issue by ecmciasabellano** [kartik-v/yii2-export#335]
I want to make big changes when exporting but I need to retain the buttons from the widget.

Is there anyway to specify the action or url for each export type when?

I have read throughout the docs but I am not sure if there are any configurations for it.

Tried using the exportConfig and specifying href on the linkOptions and options property but it is not working.

Can someone help me thanks.

**Comment by raezon** [comment]
Hello I've seen your issue you this extension contains some get a request so you will need to override the mechanisme of this extension by modifying the href by a simple js function or by  enhancing the extension
