### ISSUE TITLE
pdfConfig is being ignored

### ISSUE THREAD

**Issue by adhayward** [kartik-v/yii2-export#343]
Not sure if the issue lies in the yii2-export library or with the [yii2-mpdf](https://github.com/kartik-v/yii2-mpdf) one but it seems that the pdfConfig doesn't get applied when exporting pdfs.
I've checked the [Control Export Formats demo](https://demos.krajee.com/export-demo-dtl/specific-formats) and there the settings listed there don't apply to the PDF products (there is no header/footer and the various meta properties are not filled in.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Specify any settings in the pdfConfig, eg.
 `````
echo ExportMenu::widget([
    'exportConfig' => [
        ExportMenu::FORMAT_PDF => [
            'pdfConfig' => [
                'methods' => [
                    'SetTitle' => 'Grid Export - Krajee.com',
                    'SetSubject' => 'Generating PDF files via yii2-export extension has never been easy',
                    'SetHeader' => ['Krajee Library Export||Generated On: ' . date("r")],
                    'SetFooter' => ['|Page {PAGENO}|'],
                    'SetAuthor' => 'Kartik Visweswaran',
                    'SetCreator' => 'Kartik Visweswaran',
                    'SetKeywords' => 'Krajee, Yii2, Export, PDF, MPDF, Output, GridView, Grid, yii2-grid, yii2-mpdf, yii2-export',
                ]
            ]
        ],
    ],
``````
2. Export as pdf using the widget dropdown

## Expected behavior and actual behavior

When I follow those steps, the PDF produced uses the default config, completely ignoring every option I've tried to specify.

I was expecting the config specified to affect the PDF produced

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

#### Libraries

- jQuery version:2.2.4
- yii2-export version:1.4.2

## Isolating the problem

- [x] This bug happens [on the Control Export Formats demo page](https://demos.krajee.com/export-demo-dtl/specific-formats)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-export without other plugins.

**Comment by adhayward** [comment]
I've done some digging into this issue and I believe the issue lies in how `kartik\export\ExportWriterPdf` and it's parent class `PhpOffice\PhpSpreadsheet\Writer\Pdf\Mpdf` work.

Essentially the [save function](https://github.com/PHPOffice/PhpSpreadsheet/blob/30717fd35a768c8d02634863661fe909f142fbce/src/PhpSpreadsheet/Writer/Pdf/Mpdf.php#L27) isn't overridden and sets a lot of the properties to values retrieved from the spreadsheet. 

The settings defined in `ExportMenu::pdfConfig` get passed to `kartik\mpdf\Mpdf` but the [output function in kartik\mpdf\Mpdf](https://github.com/kartik-v/yii2-mpdf/blob/941daa73572370556710e003fae9342dd6429232/src/Pdf.php#L357) never gets called so none of the properties set in the pdfConfig propagate down to the outputted pdf file.

I'm going to have a look at overriding the save function in ExportWriterPdf in such a way as to mimic the Mpdf output function which should hopefully allow all of the config to be passed correctly. 

If I get it working I can post a Pull Request.

**Comment by adhayward** [comment]
PR #344  gets the config to pass through however I still get issues with the headers only appearing on page 1. 
I believe this is an issue with the html PhpSpreadsheet generates not being compatible with Mpdf though and not a problem with this export library.

**Comment by kartik-v** [comment]
Thanks will check.

**Comment by lloyd966** [comment]
Any idea when this might be verified, and fixed if necessary?
