### ISSUE TITLE
yii2 export config 

### ISSUE THREAD

**Issue by margeslt** [kartik-v/yii2-export#35]
I try to use from kartik-v: yii2-export (with the module grid)
git: https://github.com/kartik-v/yii2-export (grid from kartik-v: http://demos.krajee.com/grid)
Did not get to do the export setting (put delimiter, create your own name for the file);

On site:
http://demos.krajee.com/grid
written default settings:
"The default exportConfig is setup as below".

For their changes I write settings in a property: [i]exportConfig[/i] in GridView.

No results are not present, the file is exported with the default settings. And the property itself "exportConfig" successfully parsed like widget GridView, by parseExportConfig.

Since I am suffering for about a day with this, I decided to tweak these settings, the "default", but it does not give (. Settings loaded  unclear from where ((

[code]use yii\helpers\Html;
use kartik\grid\GridView;
use kartik\export\ExportMenu;

$gridColumns = [
        ['class' => 'yii\grid\SerialColumn'],
        'idproduct',
        'name',
        'mainImg',
        ['class' => 'yii\grid\ActionColumn'],
    ];
 
    // Renders a export dropdown menu
    echo ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns
    ]);

    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $gridColumns,
        'exportConfig'=> [
            GridView::CSV=>[
                'label' => 'CSV',
                'icon' => '',
                'iconOptions' => '',
                'showHeader' => false,
                'showPageSummary' => false,
                'showFooter' => false,
                'showCaption' => false,
                'filename' => 'yii',
                'alertMsg' => 'created',
                'options' => ['title' => 'Semicolon -  Separated Values'],
                'mime' => 'application/csv',
                'config' => [
                    'colDelimiter' => ";",
                    'rowDelimiter' => "\r\n",
                ], 
            ],
        ],
    ]);  [/code]

**Comment by kartik-v** [comment]
You are confusing two different export utilities.

The `ExportMenu` in **yii2-export** has its own export settings that allows you to display the entire dataProvider and does not depend nor is related to the gridview module or its settings.

The `exportConfig` in **yii2-grid** is a client level export utility in the gridview that exports the displayed table on the browser.

Both are different... so if you are using **yii2-export** set all settings in ExportMenu to control and viceversa for the **yii2-grid**.

Best is to read the docs for [yii2-export](http://demos.krajee.com/export) and [yii2-grid](http://demos.krajee.com/grid) in detail and look at the examples on usage before you start.

**Comment by divyaksnnan** [comment]
Hi Kartik I am having the same problem , i am very new to to yii2, i followed the steps given by you but not worked, could you please help me to sort it out
