### ISSUE TITLE
Missing versioned dependency on kartik-v/yii2-krajee-base

### ISSUE THREAD

**Issue by fsateler** [kartik-v/yii2-export#36]
yii2-export (transitively) depends on `kartik-v/yii2-krajee-base`, but it requires a new enough version. Installing yii2-export will not cause composer to update yii2-krajee-base to a new enough version. Please add a versioned dependency so that this happens automatically.

**Comment by kartik-v** [comment]
yii2-krajee-base is now tagged with latest release v1.7.2.

**Comment by fsateler** [comment]
Hi,

The problem is that if I have an old version of yii2-krajee-base (for
example, because I installed yii2-widgets a while ago) and then I do
`composer require yii2-export '*'` , I get errors, because
`\kartik\base\TranslationTrait` does not exist in the version of
yii2-krajee-base that I have installed.

If yii2-export added a versioned dependency, composer would upgrade
yii2-krajee-base when installing yii2-export.

I hope I am clearer this time.

Saludos

On Mon, Jan 19, 2015 at 3:43 PM, Kartik Visweswaran <
notifications@github.com> wrote:

> Closed #36 <https://github.com/kartik-v/yii2-export/issues/36>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kartik-v/yii2-export/issues/36#event-221159959>.
>



-- 

Saludos,
Felipe Sateler

**Comment by kartik-v** [comment]
Composer should automatically update `yii2-grid` and `yii2-krajee-base` whenever they are updated.

**Comment by kartik-v** [comment]
Composer should automatically update `yii2-grid` and `yii2-krajee-base` whenever they are updated.

You must run `composer update` to be sure you have the latest versions.

**Comment by fsateler** [comment]
On Mon, Jan 19, 2015 at 4:00 PM, Kartik Visweswaran <
notifications@github.com> wrote:

> Composer should automatically update yii2-grid and yii2-krajee-base
> whenever they are updated.
>
> You must run composer update to be sure you have the latest versions
>

But running composer update risks breaking the application if something has
changed. Therefore I only do it when I allocate time to do so, and not
every time I install a new package.

There is a reason composer supports versioning dependencies. It is to make
sure the required components are at the correct versions.

-- 

Saludos,
Felipe Sateler

**Comment by kartik-v** [comment]
In that case, I would suggest you manually add the "yii2-krajee-base" and "yii2-export" versions to what you need in your composer.json file.

**Comment by kartik-v** [comment]
In that case, I would suggest you add the "yii2-krajee-base" version to latest (e.g. "@dev" or "*") in your composer.json file. 

yii2-krajee-base has to be the latest for all other krajee components to work.
