### ISSUE TITLE
The export file renders "No results found" but the gridview has data

### ISSUE THREAD

**Issue by neoacevedo** [kartik-v/yii2-export#368]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-export.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/export) and [demos](http://demos.krajee.com/export-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Setting Export menu widget with the same columns and data provider as in the gridview: 
```php
$fullExport = ExportMenu::widget([
    'dataProvider' => $dataProvider, // The same data provider for the Grid View
    'columns' => $columns, // the same columns for the Grid View
    'target' => ExportMenu::TARGET_SELF,
    'exportContainer' => [
        'class' => 'btn-group mr-2 me-2'
    ],
    'template' => '{menu}',
    'exportConfig' => [
        ExportMenu::FORMAT_HTML => null,
        ExportMenu::FORMAT_EXCEL => null,
        ExportMenu::FORMAT_CSV => null,
        ExportMenu::FORMAT_TEXT => null,
        ExportMenu::FORMAT_EXCEL_X => [
            'alertMsg' => Yii::t('kvexport', 'The EXCEL export file will be generated for download.'),
        ],
        ExportMenu::FORMAT_PDF => [
            'alertMsg' => Yii::t('kvexport', 'The PDF export file will be generated for download.'),
        ],
    ],
    'dropdownOptions' => [
        'label' => 'Exportar',
        'class' => 'btn btn-outline-secondary btn-default',
        'itemsBefore' => [
            '<div class="dropdown-header">Exportar todos los datos</div>',
        ],
    ],
]);
...
<?= GridView::widget([
                            'dataProvider' => $dataProvider,
                            'filterModel' => $searchModel,
                            'containerOptions' => ['class' => 'card border-primary'],
                            'bordered' => true,
                            'striped' => true,
                            'condensed' => true,
                            'resizableColumns' => true,
                            'responsive' => true,
                            'responsiveWrap' => false,
                            'hover' => true,
                            'headerRowOptions' => ['class' => 'kv-table-header', 'color' => 'white'],
                            'tableOptions' => ['id' => 'table-cuentas'],
                            'autoXlFormat'=>true,
                            'toolbar' => [
                                // '{export}',
                                $fullExport
                            ],
                            'panel' => [
                                'type'=>'default',
                            ],
                            'columns' => $columnas
                        ]) ?>
```
2. Click on any export file option
3. To generate the file

## Expected behavior and actual behavior

The generated file only has the empty text message: "No results found".

The generated file should have at least the same data in the current grid view page.

#### Browsers

- [ ] Google Chrome
- [X] Mozilla Firefox
- [x] Microsoft Edge
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [x] Mobile

#### Libraries

- jQuery version:
- yii2-export version: dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/export-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-export without other plugins.

**Comment by neoacevedo** [comment]
In addition to this issue, if I set the `emptyText` to the export menu as `'emptyText' => $dataProvider->count,`, the rendered file will display the total count for the dataProvider, and of course, it is >=1.

**Comment by zuzuqo** [comment]
I faced the same issue. This is due to the logic of GridView and ExportMenu - it is different. Changing the query in the `dataProvider` allowed me to go further.

**Comment by kartik-v** [comment]
Check the dataProvider you pass to the GridView and ExportMenu - both are separate settings - and you need to setup the dataProvider query as per your use case - if you want to mirror the GridView and ExportMenu - ensure you pass the exact same modified dataProvider to both.
