### ISSUE TITLE
Not exporting after change to filter - possibly pjax related

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-export#46]
First worth mentioning this only issue when pjax is true.

When I change a filter value and then click to export, nothing happens - no console error nor post.

When I refresh the browser exporting now works - and with the filter applied.

Great job by the way, I previously used your grid view but had written my own export using phpexcel - now I can get rid of that and just use yours :)

Of course there is the possibility that you can't replicate the issue and it turns out to be something else of mine conflicting but heres the important bits to try and replicate anyway. If you can't replicate then I will strip away everything to find out where it goes wrong.

```
$fullExportMenu = ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
    'target' => ExportMenu::TARGET_SELF,
    'fontAwesome' => true,
    'showConfirmAlert' => false,
    'showColumnSelector' => false,
    'dropdownOptions' => [
        'label' => 'Export',
        'class' => 'btn btn-default',
    ],
]);

?>
<div class="index">
    <?= GridView::widget([
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'columns' => $gridColumns,
		'responsive' => true,
		'hover' => true,
		'bordered' => false,
		'floatHeader' => true,
                'pjax' => true,
		'panel' => [
			'heading'=>Html::tag('h3', Html::encode($this->title), ['class' => 'panel-title']),
			'type' => 'default',
			'before' => $before,
			'showFooter' => false,
			'layout' => $template,
		],
        'toolbar' => [
            $fullExportMenu,
        ]
	]); ?>
```

**Comment by kartik-v** [comment]
Note, this is because the export menu is rendered inside the grid pjax container and hence when pjax filter request overwrites the HTML markup - it breaks the export plugin. It needs to be reinitialized after pjax complete. I am providing an update for this shortly.

**Comment by kartik-v** [comment]
Ok there is a new property `ExportMenu::pjaxContainerId` added to the widget. You need to set this and `GridView::pjaxSettings['options']['id']` to the same value and everything else will happen automagically on pjax refresh.

**Comment by kartik-v** [comment]
Check an updated example using pjax in [Advanced Grid 1 scenario on demo page](http://demos.krajee.com/export-demo#grid-advanced-1).

**Comment by andrewblake1** [comment]
Hi, cheers for the fix.

Perhaps a related minor issue. If I filter by something and tab to next column so that pjax update occurs, when I export the data is unfiltered. If I refresh the browser window before export then the export works filtered - which is what I would expect.

**Comment by lubobill1990** [comment]
@kartik-v Hi, this issue is still not fixed:

https://github.com/kartik-v/yii2-export/blob/master/assets/js/kv-export-data.js#L145

Even though you try to reinitialize the widget after pjax:complete is triggered, the function listen is not called because data is not empty
