### ISSUE TITLE
Data unfiltered after pjax

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-export#48]
If I filter by something and tab to next column so that pjax update occurs, when I export the data is unfiltered. If I refresh the browser window before export then the export works filtered - which is what I would expect.

**Comment by kartik-v** [comment]
Not clear with your query.

- If you use the same dataprovider for both ExportMenu and GridView... then on filtering the gridview, the export returns filtered rows after pjax. [Check the demo](http://demos.krajee.com/export-demo?#grid-advanced-1).

- If you use different dataproviders for both ExportMenu and GridView...  then the two will be independent.

**Comment by andrewblake1** [comment]
Apols, perhaps I haven’t made the issue clear.

Have just tested on your demo page and the issue is still clear to me.
1./ filter name by “the gr”
2./ full export 2007+
3./ examine the export and I get 21 rows including heading - the last one being lord of the flies
4./ refresh the browser window
5./ from the same grid again do full export 2007+
6./ examine the export and i get 3 rows including heading with just 2 books “The Great Gatsby” and “The Grapes Of Wrath”

I wouldn’t expect to need to refresh the browser window to have the filter apply ideally - I think my users would be confused by this.

**Comment by kartik-v** [comment]
Not sure why -- the HTML and text output show filtered rows....

**Comment by kartik-v** [comment]
Not sure why.

Check with the HTML, text, and Excel95 outputs. They show filtered rows....

I think its some problem only with Excel 2007 & PDF formats.

**Comment by andrewblake1** [comment]
I see what you mean. Not what I expected - thought it was failing to post the filter variables because of something to do with pjax but that seems unlikely now … a little weird :)

If you ever need me to debug such things let me know - I feel a little rude pointing out the issues without stepping thru but am guessing you are already part way thru it and 100 times faster in your own code.

**Comment by kartik-v** [comment]
This is now resolved via #51. You can [check this in the demo](http://demos.krajee.com/export-demo?#grid-advanced-1) after clearing your browser cache and refreshing
