### ISSUE TITLE
Export in Mac OS

### ISSUE THREAD

**Issue by ipppinto** [kartik-v/yii2-export#56]
Hi,

why in Mac Os all files exported have .html. To open a excel file a have xlsx.html and I have to delete . html to open the file.

thank you.

**Comment by kartik-v** [comment]
Ensure you have the latest updated package from dev-master on this repo by cross checking the source.

**Comment by ipppinto** [comment]
Hi,

How can I see my version? And how can I configure my composer to dev-master?
