### ISSUE TITLE
showPageSummary option in yii2-export

### ISSUE THREAD

**Issue by pkjoshi** [kartik-v/yii2-export#57]
If I am using the default export feature of gridview, I am getting the page summary in the exported excel file, but then it exports in old excel format.
If I am using the export menu for export I am not getting the page summary, where I am getting the excel-2007 format, which I want.
Am I missing anything in the config?

**Comment by kartik-v** [comment]
you need to configure the page summary within export menu as well..

**Comment by buchenko** [comment]
set 'pageSummary' for column:
![default](https://user-images.githubusercontent.com/14020992/38204177-7d9605c6-36aa-11e8-8405-714ed802c7aa.png)

set 'showPageSummary' for GridView:
![default](https://user-images.githubusercontent.com/14020992/38204225-af5b97a6-36aa-11e8-8b77-9ac48b1ddcf6.png)

set 'showPageSummary' for exportConfig in ExportMenu
![default](https://user-images.githubusercontent.com/14020992/38204261-e575a728-36aa-11e8-823c-df06b7da8470.png)

but Excel file does not contain this field

What did I do wrong?

**Comment by kartik-v** [comment]
`ExportMenu` simply extends the `GridView` widget class so it should be straightforward isn't it... why are you changing the position of the property ..

It must be the same position as the `GridView` widget:

```php
echo ExportMenu::widget([
    'showPageSummary' => true,
   // other configuration options
]);
```

**Comment by buchenko** [comment]
Unfortunately, this did not help

**Comment by buchenko** [comment]
I found public function renderPageSummary() in GridView, but did not find in ExportMenu.

![default](https://user-images.githubusercontent.com/14020992/38238462-9a86fe1e-3732-11e8-98a4-71731befdadb.png)

**Comment by rtbsolutions** [comment]
you have to provide calculated value of 'footer' property for each column to render it in Excel
