### ISSUE TITLE
Kartik-v yii2-export gives different result when exporting from web and from localhost

### ISSUE THREAD

**Issue by ACME-Raafat** [kartik-v/yii2-export#58]
I have developed my Yii2 application on xampp and then I published it online. My application exports a table from the database as excel file. When I export from my local host I get the form that I want:

![export from local host](https://cloud.githubusercontent.com/assets/11060374/7065117/2eb83606-debd-11e4-836d-2ef8d1e4cbb2.png)

But when I export the same file from the web this is what I get:

![export from web](https://cloud.githubusercontent.com/assets/11060374/7065127/40f17af8-debd-11e4-8f90-666168d34559.png)

I didn't change anything in my code. I wonder what could be the problem and how can I fix this.

**Comment by kartik-v** [comment]
You would need to debug what's different.

For starters, you should check if you have the latest updated version of the yii2-export extension on your server. Just cross check with the dev-master code here.

**Comment by jomonkj** [comment]
I have same problem

**Comment by ACME-Raafat** [comment]
Hi, I'm  sorry I'm still unable to solve my problem. I would really appreciate if you post your solution once you find it.

**Comment by jomonkj** [comment]
This problem occurs when `Exporting All Data`.
and filename.extension changing to filename.extension.html
i think the problem is related to http://stackoverflow.com/questions/16805851/phpexcel-generated-excel-file-not-working-file-format-or-extension-is-invalid
 `Export Page Data`  works fine.

**Comment by kartik-v** [comment]
Cannot reproduce this - if you find something to reproduce please post here and this can be reopened if needed.

**Comment by jomonkj** [comment]
i solved this problem in my server by enabling output_buffering in php.ini.

check https://phpexcel.codeplex.com/wikipage?title=Requirements&referringTitle=Home
