### ISSUE TITLE
Error Class 'PHPExcel_Settings' not found

### ISSUE THREAD

**Issue by MaksimSkomorokh** [kartik-v/yii2-export#59]
Hi Kartik V. I've used code from Usage and getting error Class 'PHPExcel_Settings' not found. Tried versions from
"kartik-v/yii2-export": "dev-master"
and
"kartik-v/yii2-export": "*"
Pls help

**Comment by kartik-v** [comment]
Seems PHP Excel library is not getting installed or read properly ... you need to debug that.
