### ISSUE TITLE
Multiple export menus on one page

### ISSUE THREAD

**Issue by wouterbenninga** [kartik-v/yii2-export#62]
Is it possible to add multiple export menu on the same page with different data?

When I try this, the second export menu gives the data of the first, while I set another dataProvider.

**Comment by wilianto** [comment]
+1, this happens also with me.

**Comment by kartik-v** [comment]
You need to set `ExportMenu::options['id']` to a unique value for every export menu widget.

**Comment by 9uz** [comment]
i set 
`<?= 
ExportMenu::widget([
                            'dataProvider' => $dataProviderMawa,
                            'columns' => $gridColumnsMawa,
                            'options'=>['id'=>'w5'],
                            'showColumnSelector' => true,
                            'target' => '_blank',
                            'dropdownOptions' => [
                                'icon' => '<i class="glyphicon glyphicon-download-alt"></i>',
                            ]
                        ]); ?>`


and 
                      `<?=
                      ExportMenu::widget([
                            'dataProvider' => $dataProviderKarya,
                            'columns' => $gridColumns,
                            'showColumnSelector' => false,
                            'options'=>['id'=>'w1'],
                            'target' => '_blank',
                            'dropdownOptions' => [
                                'icon' => '<i class="glyphicon glyphicon-download-alt"></i>', 
                            ]
                        ]);
                        ?>`

but this is same for me, the second export menu gives the data of the first

**Comment by kartik-v** [comment]
Ok will check and update.

**Comment by kartik-v** [comment]
Check various new enhancements via #64. Also check the [updated demo for multiple export menus](http://localhost:8000/yii-kv/export-demo#multiple-export-menus).

You can also check the updated demo for [larger export files linking](http://demos.krajee.com/export-demo#large-files-link) and [larger export files streaming](http://demos.krajee.com/export-demo#large-files-stream).

**Comment by desenvolvedorindie** [comment]
I'm getting same problem in 1.3.6 version
I've checked and for some reason is exporting with part of page (HTML).

**Comment by desenvolvedorindie** [comment]
Probably related with #277.
I'm not sure

**Comment by BoguckiM** [comment]
Hello. I have this code, and even though I have set different ids, I can only downloads from the first control.

`        $index = 0;
        foreach($datas as $data) {
            $fileName = str_replace(' ', '_', $data['name'] . '__' . $data['dataProvider']->query->where[1][2] . '-' . $data['dataProvider']->query->where[2][2] . '__' . date('yy-m-d'));

            echo ExportMenu::widget([
                'bootstrap' => true,
                'dataProvider' => $data['dataProvider'],
                'filterModel' => $searchModel,
                'columns' => $gridColumns,
                'options' => [
                    'id' => 'download' . $index,
                ],
                'id' => 'download' . $index,
                'dropdownOptions' => [
                    'label' => $data['name'],
                    'class' => 'btn btn-outline-secondary btn-default'
                ],
                'exportConfig' => [
                    ExportMenu::FORMAT_PDF => false,
                    ExportMenu::FORMAT_TEXT => false,
                    ExportMenu::FORMAT_HTML => false,
                    ExportMenu::FORMAT_CSV => ['filename' => $fileName],
                    ExportMenu::FORMAT_EXCEL => ['filename' => $fileName],
                ],
               'filename' => $fileName,
               'target' => ExportMenu::TARGET_BLANK,
            ]);
            $index++;
        }`
