### ISSUE TITLE
[discussion] How to improve performance of slow yii2-export ?

### ISSUE THREAD

**Issue by panique** [kartik-v/yii2-export#63]
Hey guys,

thanks for this wonderful script! I'm using to inside several projects and the creation of the files is extremely slow. I'd like to open a small discussion on how to improve the performance of this script (as I'm experiencing performance issues even on very powerful servers).

### Example
Rendering just 100 lines of super-simple data (10 columns with simple strings) takes 5secs on a 8-core machine with 8 GB RAM (Rackspace instance). Rendering 1000 lines takes 30secs, crashing the request. I can reproduce this.

### Question:

I would like to ask the creators of the project if ...
1. this is a know problem (or just me) ?
2. is there a simple quick way to improve the speed of this script ?

Thanks a lot & have a fine day

**Comment by kartik-v** [comment]
The script uses PHPExcel library and is heavily dependent on what this library is capable of. Would recommend if you can carry out a performance test separately with the PHPExcel library with various options and find out what you are facing with regards performance and report here.

**Comment by kartik-v** [comment]
You may want to check the new enhancements primarily via #62, #64 and #69. Still the extension is limited by PHP Excel functionality - however it allows you to better control the way the files are saved and streamed. Check the updated demo for [larger export files linking](http://demos.krajee.com/export-demo#large-files-link) and [larger export files streaming](http://demos.krajee.com/export-demo#large-files-stream).

**Comment by itshakeel23** [comment]
Hi kartik. I want to ask that how can I reduce the time exporting data. I am using Export menu widget. It takes too much time to export even for 100 records. If records are more than 100 than server timeout occurs. Can you guide me in order to resolve this issue?
