### ISSUE TITLE
Buffer emulation

### ISSUE THREAD

**Issue by ptz-nerf** [kartik-v/yii2-export#64]
Hello!
Nice extension! It's not new issue, but I would like to suggest you add a buffer emulation properties or callback on save. It is useful when output_buffering is disabled or has small size.
Example: 
```php
function SaveViaTempFile($exportMenu, $writer, $filePath)  {
    $writer->save($filePath);
	$exportMenu->setHttpHeaders();
	readfile($filePath);
    @unlink($filePath);
	$exportMenu->destroyPHPExcel();
	exit();
}
```

**Comment by ptz-nerf** [comment]
Pull request: https://github.com/kartik-v/yii2-export/pull/65

**Comment by kartik-v** [comment]
Check various new enhancements via #64. Check the updated demo for [larger export files linking](http://demos.krajee.com/export-demo#large-files-link) and [larger export files streaming](http://demos.krajee.com/export-demo#large-files-stream).

**Comment by ptz-nerf** [comment]
Awesome!
PS: not yet tested.
