### ISSUE TITLE
activeQuery and each or batch

### ISSUE THREAD

**Issue by dizews** [kartik-v/yii2-export#66]
hello.

Some tables has a lots of data. Current code select all data without any limitations. but I think it will be a good if we use ```each``` (with a batch 100 or similar).

what do you think?

**Comment by kartik-v** [comment]
You need to manage this by controlling this through your query for your `dataProvider` that is used in the export .

**Comment by dizews** [comment]
I think ```$models = array_values($this->_provider->getModels());``` try to get all rows from databases.

**Comment by kartik-v** [comment]
You need to use [yii query methods](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html) like `$query->limit(100)` in your model function that returns the `dataProvider`.

**Comment by dizews** [comment]
You misunderstood me. I talk about an export all needed data without limits but with batching for queries.

```php
for ($page=0; $page < $pages; ++$page) {
    $models = $dataProvider->getModels();
    foreach ($models as $model) {
         $output = $model->id . ";".$model->name;
    }
    echo $output; //flush data to user
}
```

**Comment by kartik-v** [comment]
You can use [yii query methods](http://www.yiiframework.com/doc-2.0/guide-db-query-builder.html) like `$query->limit(100)` in your model function that returns the `dataProvider`.

But using `query->each` is an alternate approach for batch queries - not sure it will work with `dataProvider` because the `dataProvider->getModels()` will run a `query->all()` by default.

**Comment by kartik-v** [comment]
Not sure I understand how you intend this to be executed... the export menu uses a `dataProvider->getModels()` which is intended to export all rows returned in the query by the dataProvider.

The export menu has been intended to be built to export all rows in the dataProvider. You control what you need to export through the query within the `dataProvider`.

Note that the `dataProvider` for export menu  and the displayed gridview are different and not the same. So you can send in the restricted batch of data for export And show a different data set for gridview and vice versa.

What you are mentioning already exists in GridView as a pagination component - where a fixed set of rows are returned for each page... the inbuilt export functionality of `kartik\grid\GridView` offers page wise exporting already.

**Comment by kartik-v** [comment]
Not sure I understand how you intend this to be executed... the export menu uses a `dataProvider->getModels()` which is intended to export all rows returned in the query by the dataProvider.

The export menu has been built with intention to export ALL rows in the dataProvider. You control what you need to export through the query within the `dataProvider` that you set in the export menu widget.

Note that the `dataProvider` for export menu  and the displayed gridview are different and not the same. So you can send in the restricted batch of data for export and show a totally different data set for gridview and vice versa.

What you are mentioning already exists in GridView as a pagination component - where a fixed set of rows are returned and displayed for each page... the inbuilt export functionality of `kartik\grid\GridView` offers page wise exporting already.

You can build a simple form that allows you to restrict queried data that is passed to the export menu.
