### ISSUE TITLE
ExportMenu Dropdown menu error

### ISSUE THREAD

**Issue by antoniomadrigal10** [kartik-v/yii2-export#68]
The dropdown menu its not showing when the button is clicked!
I have   "kartik-v/yii2-export": "dev-master" plugin!
this is my code!
What am i doing wrong? please help!

 <?=  ExportMenu::widget([
                'dataProvider' => $dataProvider,
                'target'=> ExportMenu::TARGET_BLANK,
                'dropdownOptions' => [
                    'label' => 'Descargar Datos',
                    'class' => 'btn btn-default',
                ],
                'fontAwesome' => true,
                'emptyText'=> 'No se encontraron datos',
                'showConfirmAlert'=>true,
                'columns' => [
                   'id',             
                    'num_tarima',
                    'codigo'
                ],
             ]);
        ?>

**Comment by kartik-v** [comment]
Cannot reproduce this. Check if you have the bootstrap JS assets loaded and there is no javascript error on your page (OR conflict due to other JS plugins).

**Comment by aesnyahsan** [comment]
I am also facing this same issue.. when I add this code,
`      echo ExportMenu::widget([
            'dataProvider' => $dataProvider,
            'columns' => $gridColumns
    ]);`

all dropdown stop working...
After some testing, I realize the addition of `'js/bootstrap.min.js',` in my Asset file is conflicting with Kartik Export Menu...
In my project I need to use both of them... 
Can you please suggest any solution?
