### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by enaza** [kartik-v/yii2-export#74]
try
 > composer require kartik-v/yii2-export "1.2.2"

get
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
[RuntimeException]                                                                                                                                        
  Failed to execute git clone --mirror 'git+https://github.com/jrburke/r.js.git' '/home/amelkikh/composer/cache/vcs/git-https---github.com-jrburke-r.js.git/'  
  Cloning into bare repository '/home/amelkikh/composer/cache/vcs/git-https---github.com-jrburke-r.js.git'...                                                  
  fatal: Unable to find remote helper for 'git+https'    

Please help, thanks

**Comment by kartik-v** [comment]
This is not related to this extension. Its showing some message of some repo you have in your composer.json that cannot be reached `https://github.com/jrburke/r.js.git' `...
