### ISSUE TITLE
Export PDF problem

### ISSUE THREAD

**Issue by liyunfang** [kartik-v/yii2-export#79]
GridView can configure the properties of config pdf ,

And the ExportMenu in the PDF property can not be configured.

For example, the following configuration:

                    'config' => [
                    'methods' => [
                        'SetHeader' => [
                            ['odd' => $pdfHeader, 'even' => $pdfHeader]
                        ],
                        'SetFooter' => [
                            ['odd' => $pdfFooter, 'even' => $pdfFooter]
                        ],
                       ],.....

**Comment by kartik-v** [comment]
Check the PHP Excel Documentation for the configuration (since this extension uses PHPExcel).
