### ISSUE TITLE
Columns selector within gridview export

### ISSUE THREAD

**Issue by juanruben** [kartik-v/yii2-export#83]
Hi.. I have an issue when filtering via pajax in a gridview and trying to exporting the resulting rows only. Because I need the option to choose the columns to be exported I am using yii2-export, but it has not been possible to get the filter model from the gridview. If I set pajax => true in the gridview options it makes a conflict with Pjax::begin([]); ... Pjax::end();
I really dont know what is the best way to use ajax in my gridview, but I'm almost done with the option in the gridview. But the only issue is that I cannot get the filtered report.
It is so hard to include columns selector in the {export} component in gridview?

**Comment by kartik-v** [comment]
`yii2-export` is designed to export all rows from your data provider. You need to control the dataProvider if you need to filter specific rows.
