### ISSUE TITLE
Render my own pdf with this widget

### ISSUE THREAD

**Issue by juanruben** [kartik-v/yii2-export#85]
Hi.. I have examples about using mpdf and also I have used it with yii1.1
What I dont know is how to specify into the widget the function I want to use to render the data. There is no a simple example out there that shows the way to do that. Currently I am able to export the default pdf, but I want to do it in tables, with title, footer, etc. and dont know how to do it with this widget

**Comment by kartik-v** [comment]
This is not a pdf rendering widget. If you need one like that for that you can look at [yii2-mpdf](https://github.com/kartik-v/yii2-mpdf) extension. This extension uses PHPExcel and you can look into PHPExcel docs for configuring options.
