### ISSUE TITLE
Export to CSV is not keeping leading zeros

### ISSUE THREAD

**Issue by Monumentix** [kartik-v/yii2-export#88]
I have a string datatype for Zipcode field.  This data can have leading zeros.  When performing a CSV export, it truncates leading zeros?  The datatype is string as there are other values containing a full zip code 12345-4567 and they are being rendered valid, so why is this truncating leading zeros for a string?

**Comment by kartik-v** [comment]
Check PHP Excel documentation for formatting cells and you can set these using `onRenderDataCell` property.
