### ISSUE TITLE
Export Menu Button Not Expanding to Show Export Menu

### ISSUE THREAD

**Issue by rdsingleton** [kartik-v/yii2-export#9]
Hi, i'm fairly new to Yii development but the menu isn't displaying when I click on the button - i think the code is OK but I can't figure ok what is wrong.  The grid is showing fine just the button which doesn't work.

Thanks

Code:

```
ExportMenu::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
    'fontAwesome' => true,
    'dropdownOptions' => [
        'label' => 'Export All',
        'class' => 'btn btn-default',           
    ]
]) . "<hr>\n" .

GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => $gridColumns,
        ]
);
```

**Comment by lordrebs** [comment]
Hi sorry if this is an old issue...may i know the solution for this problem? I also encountered it now. please help

**Comment by Sakthivelkandasamy** [comment]
Karthik menu export not working in yii2 and I am using the materialize BSB Admin penal.  Please help

**Comment by juliardi** [comment]
I am having the same problem. And in my case there are no errors in the browser console.

**Comment by kartik-v** [comment]
Sorry folks - you need to debug your code. Ensure that you are NOT ENVELOPING the widgets inside a FORM tag... because both GridView and ExportMenu render their OWN FORMS and browsers will treat HTML as bad and broken if you nest forms.

**Comment by DPineault** [comment]
I was experiencing the same issue.

By trial and error I was able to identify, by commenting out individual items from the AppAsset.php (under the assets folder), that 

'vendor/bootstrap/js/bootstrap.min.js',

was causing a conflict.

I don't know if it will be the exact js file, but try disabling them one by one and testing, you may be able to identify the source of your problem in that manner.
