### ISSUE TITLE
export with colors and column groups

### ISSUE THREAD

**Issue by ANTVirGEO** [kartik-v/yii2-export#92]
Hello! 
First of all - thanks for that great project! 
My question is: How can I get xls export file from mine gridview with colors on some rows and some grouping using yii2-export? (cause i need export file with all rows in pagination (not only first page)).
Now I have 2 choises - 
1 with yii2-export and yii2-grid:
---------------------------------
echo ExportMenu::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
        'fontAwesome' => true,
        'target' => ExportMenu::TARGET_SELF,
        'showConfirmAlert' => false,
        'enableFormatter' => true,
        'asDropdown' => true,
        'clearBuffers' => true,    //без него выводится в excel в говнокодировке
        'initProvider' => true,     //инициализация всего массива данных для выгрузки, а не одной страницы
        'showColumnSelector' => true,
        'encoding' => true,
        'filename' => 'test',
        'dropdownOptions' => [
            'label' => 'Export All',
            'class' => 'btn btn-default'
        ],
        'exportConfig' => [
            ExportMenu::FORMAT_TEXT => false,
            ExportMenu::FORMAT_PDF => false,
            ExportMenu::FORMAT_HTML => false,
            ExportMenu::FORMAT_CSV => [
                'iconOptions' => ['class' => 'text-primary'],
                'linkOptions' => [],
                'mime' => 'application/csv',
                'extension' => 'csv',
                'writer' => 'CSV'
            ],
            ExportMenu::FORMAT_EXCEL => [
                'iconOptions' => ['class' => 'text-success'],
                'linkOptions' => [],
                'mime' => 'application/vnd.ms-excel',
                'extension' => 'xls',
                'writer' => 'Excel5'
            ],
            ExportMenu::FORMAT_EXCEL_X => [
                'iconOptions' => ['class' => 'text-success'],
                'linkOptions' => [],
                'mime' => 'application/application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'extension' => 'xlsx',
                'writer' => 'Excel2007'
            ],
        ]
    ]) . "<hr>\n".
    GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $gridColumns,
    ]);
------------------------
Here I have all pages in 1 files and I need it.
Second choise with only with yii2-gird:
*********************
echo DoubleHeaderGridView::widget([
    'dataProvider' => $result,
    'columns' => $columns,
    'showFooter'=> true,
    'condensed'=> true,
    'bootstrap' => true,
    'responsive' => false,//чтобы нормальная развертка по горизонтали была
    'responsiveWrap' => true,
    'exportConfig' => [
        DoubleHeaderGridView::EXCEL => ['label' => 'Save as EXCEL file',
            'showHeader' => true,
            'showPageSummary' => true,
            'showFooter' => true,
            'showCaption' => true,
            'mime' => 'application/vnd.ms-excel',
        ],
    ],
    'panel'=>[
        'type'=>'default',
        'heading'=>'Products',
    ],
    'export'=>[
        'fontAwesome'=>true,
        'showConfirmAlert'=>false,
        'target'=>DoubleHeaderGridView::TARGET_BLANK
    ],
    'footerRowOptions'=>['style'=>'background-color: d3d3d3 !important;'],
    'options'=>['style'=>"width:$widthPercent"],
    'rowOptions'=>function($model, $key, $index, $grid) use ($pager){
        if(!empty($model['errors'])){
            return ['class' => 'danger'];
        } else {
            if($index <= $pager - 1) {
                return ['style' => 'background-color: #f0f1ff!important;'];
            } else {
                $class = floor($index / $pager) % 2 ? 'background-color: #f9fcff!important;' : 'background-color: #f0f1ff!important;';
                return ['style' => $class];
            }
        }
    }
]);
************************************
Here i Have only 1 page in export, but all grouping in OpenOffice works very good (not colors - in Linux system colors not viewed in xls at all (but in Windows all colors are fine) - how I can change that?)

The main question - how I can export all pages with grouping and colors?

**Comment by kartik-v** [comment]
`yii2-export` depends on PHPExcel library to read, write, and format your excel output - you would need to check PHPExcel docs for limitations on the HTML that can be parsed. For formatting using some themes in PHP excel you can set `styleOptions` within this widget for generic formatting and also then you can format PHPExcel content using various event properties e.g. `onInitSheet`, `onRenderHeaderCell`,  `onRenderDataCell` properties
