### ISSUE TITLE
show only Excel button in Gridview

### ISSUE THREAD

**Issue by vishal46** [kartik-v/yii2-export#93]

**Comment by vishal46** [comment]
also we can't add any contain in your generated Excel file please give me answer??

**Comment by ANTVirGEO** [comment]
Hello. 
exportConfig => [
    ExportMenu::FORMAT_TEXT => false,
    ExportMenu::FORMAT_PDF => false
]
You can disable all other formats, like it says in doc.
http://demos.krajee.com/export

**Comment by vishal46** [comment]
show only Excel button not in dropdown  button??

**Comment by ANTVirGEO** [comment]
oh, not in dropbuttun)
add this 
'asDropdown' : false,
to your properties + exportConfig

**Comment by kartik-v** [comment]
yes as @ANTVirGEO mentioned and you can style it as you can with your own css
