### ISSUE TITLE
export pdf working on localhost, doesnt work on web

### ISSUE THREAD

**Issue by ikeraldasoro** [kartik-v/yii2-export#97]
Hi, I uploaded the localhost app to the web, and the pdf export function is not working. I can export to csv, txt, excel...but not pdf. Can it be a permission problem? Or what other problem?

In localhost, local ubuntu server, all is working OK.

Thanks

**Comment by kartik-v** [comment]
It seems some problem with your code setup and configuration. 

You may ask for programming tips and generic help queries in this [new Q&A forum](http://webtips.krajee.com/questions).
